### ISSUE TITLE
Realtime Database blocking UI Thread [Android]

### ISSUE THREAD

**Issue by lucasgray** [invertase/react-native-firebase#1284]
### Issue

Having issues with any call to either snapshot or observe entries in firebase blocking my UI thread on android.  I would expect my call to firebase not to block the react native UI threads.  Animations and renderings pause for 1 - 3 seconds while the firebase data is retrieved.

For example, this code

```
console.log("before getting data ");
firebase.database().ref(`routes/${userKeyToUse}/${routeKey}`)
  .once('value', snapshot => {
    console.log('after getting data');
    dispatch({type: SINGLE_ROUTE_FETCH_SUCCESS, payload: { ...snapshot.val(), id: snapshot.key }});
  });
```

Produces this output - we see that it took a bit to retrieve the node

```
07-07 09:41:16.055 24462 24889 I ReactNativeJS: before getting data 
07-07 09:41:17.306 24462 24889 I ReactNativeJS: after getting data
```

And has this affect on the UI

https://drive.google.com/file/d/1J84I5qbOi87Oirl2AYL7Skqt9cG-c6j0/view?usp=sharing

Let me know what else I can provide - I recently upgraded my version of `react-native-firebase` in order to match play services across other plugins I was using, and while I don't know for certain, it feels like these calls became a bit slower across the board.  I've played with `on('value')` vs `once('value')` with the same results.

Thanks!  Lucas  

### Environment

1. Application Target Platform: 

Android

2. Development Operating System:

macOS High Sierra

3. Build Tools:

Android 27.0.3

4. `React Native` version:

0.50.3

5. `React Native Firebase` Version:

4.2.0

6. `Firebase` Module:

4.6.2

Realtime database

7. Are you using `typescript`? 

no

I'm also debugging on a Moto g5 plus, android version 7.0

**Comment by lucasgray** [comment]
Hey @Salakar, it's kinda big - average 500kb on that page, once I grab it from firebase I cache it in redux - my initial suspicion was that I was just doing too much generally updating state/props but after bringing the data into redux every subsequent render is much smoother.  I have another use case that pulls less data, but using something like,

```
return firebase.database().ref(`routes_activity/${f}/`)
            .orderByKey()
            .startAt(oneWeekAgo+'')
            .endAt(now+'')
            .once('value', snapshot => { //stuff
```  

multiple times - much less data on every node there, but see quite a bit of jank if animations run while that one is fetching as well.

Thanks for your response!

**Comment by Salakar** [comment]
@lucasgray for tests could you get the RN performance monitor active and then on a blank screen of your app get the data as above and watch the frame rates, just want to confirm with no UI whether the FPS still tanks for 1-3 seconds like above; meaning it's most likely a performance hit from parsing on native.

**Comment by lucasgray** [comment]
For sure, here is a video to demonstrate - I edited the page that gets transitioned to to be simply a `<View/>`, while the feed page before just links (via `react-navigation` by the way if it matters) to the new page that calls the same data as earlier.  The reducer does nothing, while the action simply calls the firebase ref.

https://drive.google.com/open?id=1DX-oBWKiLd_RtGHwHzQn73-cQQh9hzIO

The second time where there is no FPS drop, I had already fetched & stored that activity in a redux reducer.

Thanks again and let me know what else I can provide from my side.

**Comment by Salakar** [comment]
@lucasgray ok thanks for confirming. A dump of the of data would be handy then I can replicate it exactly locally; as it could be something specific data wise that's bogging it down that could be better parsed/converted for example. 

You could PM me a private link on discord or twitter if it's anything sensitive:
**Discord:** Salakar#1337
**Twitter:** mikediarmid

If not then a close as possible replica would be handy instead, same size, same field types, same value types, same value lengths/size etc.

**Comment by Salakar** [comment]
Pushed up a change to address this,

> [Before change vs After change Video](https://drive.google.com/file/d/121Ouk57Ai29atadSdt_klILtDy1iTEhO/view?usp=sharing)

Closing as this is now resolved pending release 👍 Thanks @lucasgray for reporting this and helping me test things on discord.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by lucasgray** [comment]
Great work @Salakar !

**Comment by joaom182** [comment]
Same issue here, but the simple method `firestore.set()` causes UI Thread Blocking on Android too.

**Comment by ishigamii** [comment]
Has this been merged ? since which version ? I am actually experimenting this on both Android and iOS when I can't navigate till the data are loaded :s

**Comment by rufat** [comment]
The problem is still there. The .on event listener blocks the UI.

**Comment by ogtayhuseynov0** [comment]
same here :/

**Comment by mikehardy** [comment]
This issue is quite old - not disputing whether it exists or not but please open a new issue with details from the template (so we know the versions to use when attempting reproduction...) and an App.js that creates a little test data scaffold then reproduces the problem, and we can see what's going on. Without that, there will likely be no progress sorry, as we won't be able to reproduce it
