### ISSUE TITLE
 Plugin/Preset files are not allowed to export objects

### ISSUE THREAD

**Issue by rach676** [invertase/react-native-firebase#1290]
### Issue

I am running npm build ios after following the turtorial and am getting the following error

```
bundling failed: Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/rachelmoskowitz/Desktop/react-native-firebase-starter-master/node_modules/babel-preset-react-native-stage-0/decorator-support.js
```

<img width="407" alt="screen shot 2018-07-10 at 2 52 54 pm" src="https://user-images.githubusercontent.com/29984469/42531065-fabd69c4-8450-11e8-8074-8e1da6fcc569.png">

### Environment

1. Application Target Platform: 

IOS

2. Development Operating System:

macOS High Sierra 10.13.5 

3. Build Tools:

iOS Simulator

4. `React Native` version:

0.56.0

5. `React Native Firebase` Version:

4.1.0

6. `Firebase` Module:

N/A

7. Are you using `typescript`? 

no

**Comment by Salakar** [comment]
Hi @rach676, sorry about this but we don't support React Native 56 yet, it was only released 3 / 4 days ago and has quite a few breaking changes that we need to work around first before we can support it, we have started on this and it will land in React Native Firebase v5.0.0 in a week or two. RN versions < 56 are still fine.

Closing this issue for now and tracking on https://github.com/invertase/react-native-firebase/issues/1283 - thanks for reporting! 👍 

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by alimuqaddas** [comment]
The issue has been solved ?

**Comment by Salakar** [comment]
Yes on RNFB v5, releasing later today, you can use the RC in the meantime, v5.0.0-rc6 is the latest.

Thanks

**Comment by DatMoser** [comment]
Just downloaded the Firebase starter kit and getting exactly the same error again...

**Comment by DatMoser** [comment]
@Salakar Still getting the same error with RN 0.57. Just downloaded the starter kid, followed the instructions and got the exact same result again.

```
  "dependencies": {
    "fbjs": "^0.8.17",
    "react": "^16.3.2",
    "react-native": "^0.57.1",
    "react-native-firebase": "^4.3.6"
  }
```
By the way, coding on Mac with Java 8. HELP! Please... :D

**Comment by supergeekit** [comment]
> Yes on RNFB v5, releasing later today, you can use the RC in the meantime, v5.0.0-rc6 is the latest.
> 
> Thanks

Salakar is there any plans to update the starter kit soon to version 5?
