### ISSUE TITLE
Task :react-native-firebase:compileDebugJavaWithJavac FAILED cannot find symbol

### ISSUE THREAD

**Issue by qlerebours** [invertase/react-native-firebase#2220]
## Issue

Hello,

I can't install the lib on Android because of compilation errors:

```
> Task :react-native-firebase:compileDebugJavaWithJavac FAILED
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/auth/RNFirebaseAuth.java:33: error: cannot find symbol
import com.google.firebase.auth.FirebaseAuthSettings;
                               ^
  symbol:   class FirebaseAuthSettings
  location: package com.google.firebase.auth
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreCollectionReference.java:20: error: cannot find symbol
import com.google.firebase.firestore.MetadataChanges;
                                    ^
  symbol:   class MetadataChanges
  location: package com.google.firebase.firestore
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreCollectionReference.java:23: error: cannot find symbol
import com.google.firebase.firestore.Source;
                                    ^
  symbol:   class Source
  location: package com.google.firebase.firestore
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreDocumentReference.java:18: error: cannot find symbol
import com.google.firebase.firestore.MetadataChanges;
                                    ^
  symbol:   class MetadataChanges
  location: package com.google.firebase.firestore
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreDocumentReference.java:20: error: cannot find symbol
import com.google.firebase.firestore.Source;
                                    ^
  symbol:   class Source
  location: package com.google.firebase.firestore
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/ReactNativeFirebaseAppRegistrar.java:22: error: package com.google.firebase.components does not exist
import com.google.firebase.components.Component;
                                     ^
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/ReactNativeFirebaseAppRegistrar.java:23: error: package com.google.firebase.components does not exist
import com.google.firebase.components.ComponentRegistrar;
                                     ^
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/ReactNativeFirebaseAppRegistrar.java:24: error: package com.google.firebase.platforminfo does not exist
import com.google.firebase.platforminfo.LibraryVersionComponent;
                                       ^
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/ReactNativeFirebaseAppRegistrar.java:30: error: cannot find symbol
public class ReactNativeFirebaseAppRegistrar implements ComponentRegistrar {
                                                        ^
  symbol: class ComponentRegistrar
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/ReactNativeFirebaseAppRegistrar.java:32: error: cannot find symbol
  public List<Component<?>> getComponents() {
              ^
  symbol:   class Component
  location: class ReactNativeFirebaseAppRegistrar
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/auth/RNFirebaseAuth.java:247: error: cannot find symbol
    FirebaseAuthSettings firebaseAuthSettings = firebaseAuth.getFirebaseAuthSettings();
    ^
  symbol:   class FirebaseAuthSettings
  location: class RNFirebaseAuth
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/auth/RNFirebaseAuth.java:247: error: cannot find symbol
    FirebaseAuthSettings firebaseAuthSettings = firebaseAuth.getFirebaseAuthSettings();
                                                            ^
  symbol:   method getFirebaseAuthSettings()
  location: variable firebaseAuth of type FirebaseAuth
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/auth/RNFirebaseAuth.java:1536: error: cannot find symbol
              Utils.timestampToUTC(tokenResult.getAuthTimestamp()),
                                              ^
  symbol:   method getAuthTimestamp()
  location: variable tokenResult of type GetTokenResult
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/auth/RNFirebaseAuth.java:1542: error: cannot find symbol
              Utils.timestampToUTC(tokenResult.getExpirationTimestamp()),
                                              ^
  symbol:   method getExpirationTimestamp()
  location: variable tokenResult of type GetTokenResult
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/auth/RNFirebaseAuth.java:1548: error: cannot find symbol
              Utils.timestampToUTC(tokenResult.getIssuedAtTimestamp()),
                                              ^
  symbol:   method getIssuedAtTimestamp()
  location: variable tokenResult of type GetTokenResult
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/auth/RNFirebaseAuth.java:1554: error: cannot find symbol
              tokenResult.getClaims(),
                         ^
  symbol:   method getClaims()
  location: variable tokenResult of type GetTokenResult
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/auth/RNFirebaseAuth.java:1560: error: cannot find symbol
              tokenResult.getSignInProvider(),
                         ^
  symbol:   method getSignInProvider()
  location: variable tokenResult of type GetTokenResult
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/messaging/RNFirebaseMessagingService.java:21: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/messaging/RNFirebaseMessaging.java:137: error: void cannot be dereferenced
      .addOnCompleteListener(new OnCompleteListener<Void>() {
      ^
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/messaging/RNFirebaseMessaging.java:157: error: void cannot be dereferenced
      .addOnCompleteListener(new OnCompleteListener<Void>() {
      ^
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/perf/RNFirebasePerformance.java:67: error: cannot find symbol
    Integer value = Long.valueOf(getOrCreateTrace(identifier).getLongMetric(metricName)).intValue();
                                                             ^
  symbol:   method getLongMetric(String)
  location: class Trace
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/perf/RNFirebasePerformance.java:78: error: cannot find symbol
    getOrCreateTrace(identifier).incrementMetric(metricName, incrementBy.longValue());
                                ^
  symbol:   method incrementMetric(String,long)
  location: class Trace
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/perf/RNFirebasePerformance.java:101: error: cannot find symbol
    getOrCreateTrace(identifier).putMetric(metricName, value.longValue());
                                ^
  symbol:   method putMetric(String,long)
  location: class Trace
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/FirestoreSerialize.java:488: error: cannot find symbol
        return FieldValue.increment(fieldValueMap.getDouble(TYPE_FIELDVALUE_ELEMENTS));
                         ^
  symbol:   method increment(double)
  location: class FieldValue
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/FirestoreSerialize.java:497: error: cannot find symbol
        return FieldValue.arrayUnion(parseReadableArray(firestore, elements).toArray());
                         ^
  symbol:   method arrayUnion(Object[])
  location: class FieldValue
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/FirestoreSerialize.java:502: error: cannot find symbol
        return FieldValue.arrayRemove(parseReadableArray(firestore, elements).toArray());
                         ^
  symbol:   method arrayRemove(Object[])
  location: class FieldValue
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestore.java:460: error: cannot find symbol
      firestoreSettings.setTimestampsInSnapshotsEnabled(settings.getBoolean("timestampsInSnapshots"));
                       ^
  symbol:   method setTimestampsInSnapshotsEnabled(boolean)
  location: variable firestoreSettings of type Builder
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreCollectionReference.java:70: error: cannot find symbol
    Source source;
    ^
  symbol:   class Source
  location: class RNFirebaseFirestoreCollectionReference
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreCollectionReference.java:74: error: cannot find symbol
        source = Source.SERVER;
                 ^
  symbol:   variable Source
  location: class RNFirebaseFirestoreCollectionReference
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreCollectionReference.java:76: error: cannot find symbol
        source = Source.CACHE;
                 ^
  symbol:   variable Source
  location: class RNFirebaseFirestoreCollectionReference
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreCollectionReference.java:78: error: cannot find symbol
        source = Source.DEFAULT;
                 ^
  symbol:   variable Source
  location: class RNFirebaseFirestoreCollectionReference
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreCollectionReference.java:81: error: cannot find symbol
      source = Source.DEFAULT;
               ^
  symbol:   variable Source
  location: class RNFirebaseFirestoreCollectionReference
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreCollectionReference.java:129: error: cannot find symbol
      MetadataChanges metadataChanges;
      ^
  symbol:   class MetadataChanges
  location: class RNFirebaseFirestoreCollectionReference
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreCollectionReference.java:134: error: cannot find symbol
        metadataChanges = MetadataChanges.INCLUDE;
                          ^
  symbol:   variable MetadataChanges
  location: class RNFirebaseFirestoreCollectionReference
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreCollectionReference.java:136: error: cannot find symbol
        metadataChanges = MetadataChanges.EXCLUDE;
                          ^
  symbol:   variable MetadataChanges
  location: class RNFirebaseFirestoreCollectionReference
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreCollectionReference.java:194: error: cannot find symbol
            query = query.whereArrayContains(fieldPath, value);
                         ^
  symbol:   method whereArrayContains(String,Object)
  location: variable query of type Query
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreCollectionReference.java:221: error: cannot find symbol
            query = query.whereArrayContains(fieldPath, value);
                         ^
  symbol:   method whereArrayContains(FieldPath,Object)
  location: variable query of type Query
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreDocumentReference.java:75: error: cannot find symbol
    Source source;
    ^
  symbol:   class Source
  location: class RNFirebaseFirestoreDocumentReference
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreDocumentReference.java:80: error: cannot find symbol
        source = Source.SERVER;
                 ^
  symbol:   variable Source
  location: class RNFirebaseFirestoreDocumentReference
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreDocumentReference.java:82: error: cannot find symbol
        source = Source.CACHE;
                 ^
  symbol:   variable Source
  location: class RNFirebaseFirestoreDocumentReference
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreDocumentReference.java:84: error: cannot find symbol
        source = Source.DEFAULT;
                 ^
  symbol:   variable Source
  location: class RNFirebaseFirestoreDocumentReference
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreDocumentReference.java:87: error: cannot find symbol
      source = Source.DEFAULT;
               ^
  symbol:   variable Source
  location: class RNFirebaseFirestoreDocumentReference
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreDocumentReference.java:140: error: cannot find symbol
      MetadataChanges metadataChanges;
      ^
  symbol:   class MetadataChanges
  location: class RNFirebaseFirestoreDocumentReference
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreDocumentReference.java:145: error: cannot find symbol
        metadataChanges = MetadataChanges.INCLUDE;
                          ^
  symbol:   variable MetadataChanges
  location: class RNFirebaseFirestoreDocumentReference
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreDocumentReference.java:147: error: cannot find symbol
        metadataChanges = MetadataChanges.EXCLUDE;
                          ^
  symbol:   variable MetadataChanges
  location: class RNFirebaseFirestoreDocumentReference
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/RNFirebaseModule.java:66: error: cannot find symbol
      firebaseApp.delete();
                 ^
  symbol:   method delete()
  location: variable firebaseApp of type FirebaseApp
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/functions/RNFirebaseFunctions.java:64: error: no suitable method found for getInstance(FirebaseApp,String)
    FirebaseFunctions functionsInstance = FirebaseFunctions.getInstance(firebaseApp, region);
                                                           ^
    method FirebaseFunctions.getInstance(FirebaseApp) is not applicable
      (actual and formal argument lists differ in length)
    method FirebaseFunctions.getInstance() is not applicable
      (actual and formal argument lists differ in length)
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/functions/RNFirebaseFunctions.java:65: error: cannot find symbol
    functionsInstance.useFunctionsEmulator(origin);
                     ^
  symbol:   method useFunctionsEmulator(String)
  location: variable functionsInstance of type FirebaseFunctions
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/functions/RNFirebaseFunctions.java:91: error: no suitable method found for getInstance(FirebaseApp,String)
    FirebaseFunctions functionsInstance = FirebaseFunctions.getInstance(firebaseApp, region);
                                                           ^
    method FirebaseFunctions.getInstance(FirebaseApp) is not applicable
      (actual and formal argument lists differ in length)
    method FirebaseFunctions.getInstance() is not applicable
      (actual and formal argument lists differ in length)
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/ReactNativeFirebaseAppRegistrar.java:31: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/ReactNativeFirebaseAppRegistrar.java:34: error: cannot find symbol
      LibraryVersionComponent.create(
      ^
  symbol:   variable LibraryVersionComponent
  location: class ReactNativeFirebaseAppRegistrar
Note: /home/qlerebours/Projects/MyProject/my-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/notifications/DisplayNotificationTask.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
51 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-firebase:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 55s
62 actionable tasks: 62 executed
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: ./gradlew app:installDebug. Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

---

### Android

<details><summary>
I can't build on Android. I tried with différent versions (version 5 and 6 of the library).
</summary>
<p>

#### `android/build.gradle`:

```groovy
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesAuthVersion = "16.0.1"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
        classpath 'com.google.gms:google-services:4.2.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()

        configurations.all {
            resolutionStrategy.eachDependency { DependencyResolveDetails details ->
                def requested = details.requested
                if (requested.group == 'com.google.android.gms') {
                    details.useVersion '12.0.1'
                }
                if (requested.group == 'com.google.firebase') {
                    details.useVersion '12.0.1'
                }
            }
        }

        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```

#### `android/app/build.gradle`:

```groovy
apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.mypackage"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 32
        versionName "2.2.0.1"
        ndk {
          abiFilters "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    implementation project(':react-native-firebase')
    implementation "com.google.android.gms:play-services-base:16.1.0"
    implementation('com.google.android.gms:play-services-auth:16.0.1')
    implementation "com.google.firebase:firebase-core:16.0.8"
    implementation "com.google.firebase:firebase-messaging:17.5.0"
    implementation project(':react-native-onesignal')
    implementation project(':react-native-video')
    implementation project(':react-native-device-info')
    implementation project(':@react-native-community_async-storage')
    implementation 'com.facebook.android:facebook-android-sdk:4.34.0'
    implementation project(':react-native-fbsdk')
    implementation project(':react-native-google-signin')
    implementation project(':react-native-svg')
    implementation project(':react-native-google-fit')
    implementation project(':react-native-gesture-handler')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation project(':react-native-linear-gradient')
    implementation project(":react-native-google-signin")
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
package com.mypackage;

import android.app.Application;

import com.facebook.react.ReactApplication;
import io.invertase.firebase.RNFirebasePackage;
import com.geektime.rnonesignalandroid.ReactNativeOneSignalPackage;
import com.brentvatne.react.ReactVideoPackage;
import com.learnium.RNDeviceInfo.RNDeviceInfo;
import com.reactnativecommunity.asyncstorage.AsyncStoragePackage;
import com.facebook.reactnative.androidsdk.FBSDKPackage;
import co.apptailor.googlesignin.RNGoogleSigninPackage;
import com.horcrux.svg.SvgPackage;
import com.reactnative.googlefit.GoogleFitPackage;
import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;
import com.BV.LinearGradient.LinearGradientPackage;
import co.apptailor.googlesignin.RNGoogleSigninPackage;

import com.facebook.CallbackManager;
import com.facebook.FacebookSdk;
import com.facebook.appevents.AppEventsLogger;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private static CallbackManager mCallbackManager = CallbackManager.Factory.create();

  protected static CallbackManager getCallbackManager() {
    return mCallbackManager;
  }

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new RNFirebasePackage(),
            new ReactNativeOneSignalPackage(),
          new ReactVideoPackage(),
          new RNDeviceInfo(),
          new AsyncStoragePackage(),
          new FBSDKPackage(mCallbackManager),
          new SvgPackage(),
          new GoogleFitPackage(BuildConfig.APPLICATION_ID),
          new RNGestureHandlerPackage(),
          new LinearGradientPackage(),
          new RNGoogleSigninPackage()
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>
I'm using ReactNative 0.59.5 and react-native-firebase 5.3.1, but I also tried with the latest version of V5 and the V6.
</summary>
<p>

**`react-native info` output:**

```
 React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
      Memory: 253.67 MB / 15.35 GB
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 8.15.1 - ~/.nvm/versions/node/v8.15.1/bin/node
      Yarn: 1.15.2 - ~/.nvm/versions/node/v8.15.1/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.15.1/bin/npm
    SDKs:
      Android SDK:
        API Levels: 19, 23, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1

```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - Core
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Thanks for your work and maybe helping me

**Comment by mikehardy** [comment]
Examine how https://github.com/mikehardy/rnfbdemo works, and do what it does - there are no complication issues (it's verified by CI all the time). Sorry to be brief, but I do believe that repo will shed light

**Comment by sathishu37** [comment]
@qlerebours  Same Error

**Comment by mikehardy** [comment]
probably not using compatible versions from the compatibility chart in the getting started guide or if the gradle file is the same, I don't even see the firestore dependency included so it can't find the classes

**Comment by qlerebours** [comment]
Thats the problem, I didn't include firestore because I don't need this dependency.
I just need the Analytics package.
I tried with your example that worked but picking the same dependencies, I couldnt make my project work. I'd like to find out the issue before re-creating the project from zero and copy pasting the sources

**Comment by qlerebours** [comment]
Thats the problem, I didn't include firestore because I don't need this dependency.
I just need the Analytics package.
I tried with your example that worked but picking the same dependencies, I couldnt make my project work. I'd like to find out the issue before re-creating the project from zero and copy pasting the sources

**Comment by MayoudP** [comment]
Same error here 🤷🏻‍♂️

**Comment by mikehardy** [comment]
Post a reproduction based off rnfbdemo linked above that shows a compile fail and I can investigate. But I can´t reproduce

**Comment by RonenMars** [comment]
Same here

**Comment by mikehardy** [comment]
Same here responses in open source are similar to spam, there is still no reproduction, but now I have more notifications. Do you have more details or a reproduction to advance the issue? If not, you may subscribe using the button on the right for updates, or add “weight” to the issue by adding reactions

**Comment by isaquebc** [comment]
Same here

**Comment by DerekFei** [comment]
same here

**Comment by sam17896** [comment]
same here

**Comment by SebDuf** [comment]
Have you found a solution yet? I'm getting very similar errors and have no clue what to do.

Here's my stacktrace: 

```
 Task :react-native-firebase:compileDebugJavaWithJavac FAILED
*project path*/mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotificationManager.java:231: error: cannot find symbol
      return createChannelGroupMap(notificationManager.getNotificationChannelGroup(channelGroupId));
                                                      ^
  symbol:   method getNotificationChannelGroup(String)
  location: variable notificationManager of type NotificationManager
*project path*/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotificationManager.java:331: error: cannot find symbol
        notificationChannelGroup.setDescription(description);
                                ^
  symbol:   method setDescription(String)
  location: variable notificationChannelGroup of type NotificationChannelGroup
*project path*/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotificationManager.java:407: error: cannot find symbol
        writableMap.putString("description", notificationChannelGroup.getDescription());
                                                                     ^
  symbol:   method getDescription()
  location: variable notificationChannelGroup of type NotificationChannelGroup
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors

FAILURE: Build failed with an exception.
```

**Comment by Rezaramdhanisti** [comment]
same here, installed react-native-firebase 5.5.6 on project react-native 0.59.10. 
Link the android, implement gradle . when build getting same error.

**Comment by mikehardy** [comment]
works fine for me - here is is start to finish https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-rn59.sh

**Comment by hackrx** [comment]
Hello I am getting this error in my cmd:-

`
> Task :@react-native-firebase_app:compileDebugJavaWithJavac
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libfb.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libglog_init.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libhermes-executor-debug.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libhermes-executor-release.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libhermes-inspector.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libimagepipeline.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libjsc.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libjsijniprofiler.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libnative-imagetranscoder.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libreactnativeblob.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libreactnativejni.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libyoga.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libc++_shared.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libfb.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libglog_init.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libhermes-executor-release.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libimagepipeline.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libjsc.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libjscexecutor.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libjsinspector.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libnative-filters.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libnative-imagetranscoder.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libreactnativejni.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libyoga.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libc++_shared.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libfb.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libfolly_futures.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libfolly_json.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libglog.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libglog_init.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libhermes-executor-debug.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libhermes-executor-release.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libhermes-inspector.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libimagepipeline.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libjsc.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libjscexecutor.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libjsijniprofiler.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libjsinspector.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libnative-filters.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libnative-imagetranscoder.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libreactnativeblob.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libreactnativejni.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libyoga.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libc++_shared.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libfb.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libfolly_futures.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libglog.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libglog_init.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libhermes-executor-debug.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libhermes-executor-release.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libhermes-inspector.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libimagepipeline.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libjsc.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libjscexecutor.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libjsijniprofiler.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libjsinspector.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libnative-filters.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libnative-imagetranscoder.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libreactnativeblob.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libreactnativejni.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libyoga.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.

> Task :app:stripDebugDebugSymbols
Compatible side by side NDK version was not found.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libc++_shared.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libfolly_futures.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libfolly_json.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libglog.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libjscexecutor.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libjsinspector.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libnative-filters.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libfolly_futures.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libfolly_json.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libglog.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libhermes-executor-debug.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libhermes-inspector.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libjsijniprofiler.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libreactnativeblob.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\Users\user\Desktop\try\testapp2\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libfolly_json.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.

> Task :app:installDebug
07:49:44 V/ddms: execute: running am get-config
07:49:45 V/ddms: execute 'am get-config' on 'J8AAGF057652LAJ' : EOF hit. Read: -1
07:49:45 V/ddms: execute: returning
Installing APK 'app-debug.apk' on 'ASUS_X00TD - 9' for app:debug
07:49:45 D/app-debug.apk: Uploading app-debug.apk onto device 'J8AAGF057652LAJ'
07:49:45 D/Device: Uploading file onto device 'J8AAGF057652LAJ'
07:49:45 D/ddms: Reading file permision of C:\Users\user\Desktop\try\testapp2\android\app\build\outputs\apk\debug\app-debug.apk as: rwx------
07:49:46 V/ddms: execute: running pm install -r -t "/data/local/tmp/app-debug.apk"
07:49:50 V/ddms: execute 'pm install -r -t "/data/local/tmp/app-debug.apk"' on 'J8AAGF057652LAJ' : EOF hit. Read: -1
07:49:50 V/ddms: execute: returning
07:49:50 V/ddms: execute: running rm "/data/local/tmp/app-debug.apk"
07:49:50 V/ddms: execute 'rm "/data/local/tmp/app-debug.apk"' on 'J8AAGF057652LAJ' : EOF hit. Read: -1
07:49:50 V/ddms: execute: returning
Installed on 1 device.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.4/userguide/command_line_interface.html#sec:command_line_warnings`

here is my buid.gradle file of android/build.gradle
`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
    }
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.2'
        classpath 'com.google.gms:google-services:4.2.0'
        
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

`
Here is android/app/build.gradle
`apply plugin: "com.android.application"

import com.android.build.OutputFile


def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.testapp2"
        multiDexEnabled true
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        aaptOptions{
            noCompress "tflite","model"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation 'com.android.support:multidex:1.0.3'     //Enable multi Dex

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
apply plugin: 'com.google.gms.google-services'
`

here is what I am using inside App.js file
`import React, { Component } from "react";
import firestore from "@react-native-firebase/firestore";`
I am following the all procedure which is mentioning in the docs but it is not working for me :(
Also I am getting error on js server 
`
error: bundling failed: Error: Unable to resolve module `@react-native-firebase/firestore` from `Components\Login\Login.js`: @react-native-firebase/firestore could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (C:\Users\user\Desktop\try\testapp2\node_modules\react-native\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (C:\Users\user\Desktop\try\testapp2\node_modules\react-native\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (C:\Users\user\Desktop\try\testapp2\node_modules\react-native\node_modules\metro\src\node-haste\DependencyGraph.js:282:16)
    at Object.resolve (C:\Users\user\Desktop\try\testapp2\node_modules\react-native\node_modules\metro\src\lib\transformHelpers.js:267:42)
    at C:\Users\user\Desktop\try\testapp2\node_modules\react-native\node_modules\metro\src\DeltaBundler\traverseDependencies.js:426:31
    at Array.map (<anonymous>)
    at resolveDependencies (C:\Users\user\Desktop\try\testapp2\node_modules\react-native\node_modules\metro\src\DeltaBundler\traverseDependencies.js:423:18)
    at C:\Users\user\Desktop\try\testapp2\node_modules\react-native\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\user\Desktop\try\testapp2\node_modules\react-native\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)` 

@react-native-firebase/firestore could not be found within the project.
I have already installed it, but still facing errors, please somebody help me.

**Comment by mikehardy** [comment]
@hackrx 

1. this is a closed issue for a long long time, posting on closed issues is bad form - you should open a new issue with all information requested in new issue templates
1. your formatting is not valid markdown, if you want to enclose large amounts of text you use triple-ticks ('```') followed ideally by the language you are quoting (groovy for gradle, javascript, etc) - I have fixed your comment so the formatting is readable
1. your gradle "errors" are not errors. They are warnings. You'll note the command succeeds. You'll see on stackoverflow how to resolve this (hint: you need to install the Android NDK on your development machine so it can successfully strip symbols from native binaries)
1. Your javascript error looks like you have not installed a module, and it's listed in the error message - if you install `@react-native-firebase/firestore` I'm guessing it will work.

**Comment by windhamwong** [comment]
I believe the issue is still there but you sent out a link saying it can solve the issue but it never helps at all because of the situation difference. You closed the issue ticket and claimed closed to stop others to discuss is very unpolite.

**Comment by hackrx** [comment]
Hey @windhamwong I have solved this issue, please consider the following cases
1.Make sure your package.json file under dependency you have `react-native-firebase/firestore`.
2..Make sure you have linked your project and modified its files (if you are using rn < 0.60)
3.Close the JS server.
4.run `npm cache clean --force`
5.cd android && ./gradlew clean
6.Now again run the `npm run android`, I hope this will work now.

**Comment by mikehardy** [comment]
@windhamwong you must understand we are volunteers, I provide incredibly detailed solutions that people don't follow and yet I am considered rude? That's not the world I live in, sorry

**Comment by CristoRibeiro** [comment]
good night guys, i was having the same problem. In my case i resolved with follow command: adb uninstall "package_name".
Hope this helps

**Comment by mikehardy** [comment]
@iamabdulhaseeb you might like [react-native-clean-project](https://github.com/pmadruga/react-native-clean-project/) in the future - `npx react-native-clean-project`, does those things and lots of other things you'd never think to do which can also help clear up random build failures
