### ISSUE TITLE
(:fire:) Unable to install with RN 0.59.9

### ISSUE THREAD

**Issue by frodoe7** [invertase/react-native-firebase#2329]
## Issue
It's the fourth time to remove and reinstall RNF again and follow the docs carefully
but different errors fire in my face ,

last one is
> No known class method for selector 'setAnalyticsCollectionEnabled:'

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WOFA' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WOFA
  platform :ios, '9.0'
  pod 'Firebase/Core', '~> 5.3.0'

  target 'WOFATests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'WOFA-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WOFA-tvOS

  target 'WOFA-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

```

#### `AppDelegate.m`:

```objc
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <Firebase.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"WOFA"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end
```

</p>
</details>

---

## Android

I'm not targeting Android now

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 1.99 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `5.5.4`
- **`Firebase` module(s) you're using that has the issue:**
  - `Core`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

**Comment by mikehardy** [comment]
that was involved with the changes in RNFB v5.5.x - the compatibility matrix on the getting started page shows the pods you have to use for the version of RNFB you are trying

**Comment by frodoe7** [comment]
> that was involved with the changes in RNFB v5.5.x - the compatibility matrix on the getting started page shows the pods you have to use for the version of RNFB you are trying

So , what should I do , my client work is delayed now

**Comment by Ehesp** [comment]
@frodoe7 upgrade your dependencies.

**Comment by frodoe7** [comment]
Like someone said before
I kept trying till running in success
I even don't remember what was the issue and how I fixed it
anyway , I gonna close the issue

**Comment by jsmile1994** [comment]
Hello Mr. Frodoe7,
Could you tell me which version of RN and react-native-firebase you are using?
I cannot setup it well with react-native 0.59.9 and rn-firebase 5.5.6.
I'm following this guide, but still fail: https://dev-yakuza.github.io/en/react-native/react-native-firebase-admob/
Please share your podfile if you can.
Thank you!

**Comment by mikehardy** [comment]
You will want something like this https://github.com/mikehardy/rnfbdemo/blob/master/PodfileRN59

But you will probably want pod 6.13.0 (current)

**Comment by mikehardy** [comment]
@jsmile1994 you might like to see the whole set of steps to integrate actually, if you are integrating the first time. It is not easy on RN59 https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-rn59.sh
