### ISSUE TITLE
🔥 [v6] Casting error from JS to native when calling auth().verifyPhoneNumber(phoneNumber)

### ISSUE THREAD

**Issue by AliAllaf** [invertase/react-native-firebase#2639]
## Issue

When calling `auth().verifyPhoneNumber(phoneNumber)` I get the following error:
`java.lang.Double cannot be cast to java.lang.String`

I traced the error back and I think it's in this line [PhoneAuthListener.js#L53](https://github.com/invertase/react-native-firebase/blob/master/packages/auth/lib/PhoneAuthListener.js#L53) where the `this._phoneAuthRequestId` is passed as number but the method in java  [ReactNativeFirebaseAuthModule.java#L980](https://github.com/invertase/react-native-firebase/blob/master/packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java#L980) is expecting it as string

Currently I patched the code locally by converting the `this._phoneAuthRequestId` to string before passing it to the native java method 

 

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 4.47 GB / 11.87 GB
  Binaries:
    Node: 10.16.2 - C:\Users\Ali\AppData\Local\Temp\yarn--1569487673189-0.21848002575558767\node.CMD
    Yarn: 1.17.3 - C:\Users\Ali\AppData\Local\Temp\yarn--1569487673189-0.21848002575558767\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.0.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Auth`
- **Are you using `TypeScript`?**
  - `Y`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by yogeshkotadiya** [comment]
I can confirm this bug on v6, It's working on v5.

**Comment by mikehardy** [comment]
Anyone care to PR the change and/or share a patch-package patch file for others?

**Comment by r0b0t3d** [comment]
It happens on iOS as well. Got this error
```
JSON value '0' of type NSNumber cannot be converted to NSString
```
PhoneAuthListener.js
```
if (isIOS) {
  this._auth.native.verifyPhoneNumber(phoneNumber, this._phoneAuthRequestId);
}

RCT_EXPORT_METHOD(verifyPhoneNumber:
  (FIRApp *) firebaseApp
    :(NSString *) phoneNumber
    :(NSString *) requestKey
) {
}
```

**Comment by mikehardy** [comment]
Thanks for the extra information @r0b0t3d

**Comment by pierregoutheraud** [comment]
I need a quick fix for that so I tried patching it locally by converting `this._phoneAuthRequestId` to a string.
There is a second problem: When the verification fails and triggers `_verificationFailedHandler` it uses `NativeFirebaseError` which is undefined.

**Comment by Salakar** [comment]
Hey 👋 this issue should now be fixed in v6.0.1, thanks. [release notes](https://invertase.io/oss/react-native-firebase/releases/v6.0.1)

**Comment by yogeshkotadiya** [comment]
After updating to 6.0.1, I'm getting this error
```js
try {
	const { code } = await auth().verifyPhoneNumber(phoneNumber)
} catch (error){
	...
}
```
![Screenshot_1570612120](https://user-images.githubusercontent.com/9676379/66468346-a2002c80-eaa3-11e9-9ddc-fad45d80d69e.jpg)

**Comment by Salakar** [comment]
@yogeshkotadiya have pushed up a change above to fix that, will be there in the next release this week.

**Comment by yogeshkotadiya** [comment]
@Salakar Thanks for the quick patch but now `verifyPhoneNumber` Promise does not resolve or rejects `phoneAuthSnapShot`.

This is the error I'm getting,

```bash
[TypeError: undefined is not an object (evaluating 'this._promise.then.bind')]
```

Currently, the only way to access `phoneAuthSnapShot` is by using `.on`.

I want to use async/await.
```js
try {
	const { code } = await auth().verifyPhoneNumber(phoneNumber)
} catch (error){
	console.log(error) // [TypeError: undefined is not an object (evaluating 'this._promise.then.bind')]
}
```

https://github.com/invertase/react-native-firebase/blob/c518bb6e6f7232cc84f666964cdd8726f885bb77/packages/auth/lib/PhoneAuthListener.js#L213-L227

**Comment by adrienbkr** [comment]
Hi everyone,
Some news for this issues ?

**Comment by Salakar** [comment]
Fix is now live in v6.0.4. Thanks

**Comment by NitishSystango** [comment]
> It happens on iOS as well. Got this error
> 
> ```
> JSON value '0' of type NSNumber cannot be converted to NSString
> ```
> 
> PhoneAuthListener.js
> 
> ```
> if (isIOS) {
>   this._auth.native.verifyPhoneNumber(phoneNumber, this._phoneAuthRequestId);
> }
> 
> RCT_EXPORT_METHOD(verifyPhoneNumber:
>   (FIRApp *) firebaseApp
>     :(NSString *) phoneNumber
>     :(NSString *) requestKey
> ) {
> }
> ```

I am getting `JSON value '0' of type NSNumber cannot be converted to NSString` message in iOS when I back from background. I just implement cloud messaging I am not using phone number related method.
