### ISSUE TITLE
Database error code

### ISSUE THREAD

**Issue by alexisbg** [invertase/react-native-firebase#430]
### Environment

1. Application Target Platform: **Android**

2. Development Operating System: **Windows 10**

3. Build Tools: **Android SDK 23**

4. React Native version: **0.47.3**

5. RNFirebase Version: **react-native-firebase@2.2.1**

6. Firebase Module: **Database**

If I try to connect to a Firebase database but willingly without the required permissions, an error is throwed when the "on" listener is called:
```js
try {
  const ref = firebase.database().ref('profiles');
  ref.on('value', (snapshot) => console.log(snapshot.val());
}
catch (error) {
  console.log(error);
}
```
The error looks like this:
```js
Object {message: "Permission denied", details: "", code: -3, path: "profiles", listenerId: 1, …}
code:-3
details:""
listenerId:1
message:"Permission denied"
path:"profiles"
refId:3
```
The returned error.code is -3 which corresponds to the [Android API value](https://firebase.google.com/docs/reference/android/com/google/firebase/database/DatabaseError.html#PERMISSION_DENIED). But working directly with digit error codes is unsafe especially since the digit value will be different on iOS (I guess it will be 1).

In RNFirebase repo, there are these 2 test files which work with a string error code:
[tests/src/tests/database/ref/onceTests.js#L65](https://github.com/invertase/react-native-firebase/blob/0fc7f7aabbc3743be98a5716ade2cfa3f07bb844/tests/src/tests/database/ref/onceTests.js#L65)
[tests/src/tests/database/ref/on/onValueTests.js#L345](https://github.com/invertase/react-native-firebase/blob/0fc7f7aabbc3743be98a5716ade2cfa3f07bb844/tests/src/tests/database/ref/on/onValueTests.js#L345)

The **'database/permission-denied'** seems resulting of [getJSError](https://github.com/invertase/react-native-firebase/blob/ceedf9b85aed2f66954a3ccdcdf7e23e8715ee0e/android/src/main/java/io/invertase/firebase/database/RNFirebaseDatabase.java#L556) and [getCodeWithService](https://github.com/invertase/react-native-firebase/blob/ceedf9b85aed2f66954a3ccdcdf7e23e8715ee0e/android/src/main/java/io/invertase/firebase/database/RNFirebaseDatabase.java#L545) methods.

How can I get errors which include string error codes instead of digits ?
Maybe I forgot to link something?

**Comment by Salakar** [comment]
Hello,

See the cancelOrCallbackContext arg on the docs: https://firebase.google.com/docs/reference/js/firebase.database.Query#on

2nd arg as a function will give you a correct error - if not then it might be a bug for us to look at, but should be working.

**Comment by alexisbg** [comment]
Thanks @Salakar for the clue.

Unfortunately if I call cancelOrCallbackContext parameter:
```js
const ref = firebase.database().ref('profiles');
ref.on('value',
  (snapshot) => console.log(snapshot.val()),
  (error) => console.log(error)
);
```

The error code is still the same digit:
```
Error: permission_denied at /profiles: Client doesn't have permission to access the desired data.
code:-3
details:""
message:"permission_denied at /profiles: Client doesn't have permission to access the desired data."
modifiers:undefined
path:"profiles"
```

**Comment by Salakar** [comment]
Just realised that you're on v2, there was a lot of work done on v3 (http://invertase.link/next) to standardise error codes across the board and to bring them in line with the web codes

**Comment by Salakar** [comment]
In terms of the issue on v2, v3 is currently our main priority right now due to time constraints. Back-porting the error changes from v3 to v2 is also no small feat unfortunately. 

We'll park this one for now and consider back-porting the changes at a later date. But v3 in general is in a far better state than v2, so definitely worth the switch :)
