### ISSUE TITLE
Task :react-native-firebase_app:compileDebugJavaWithJavac

### ISSUE THREAD

**Issue by Chandravardhan8998** [invertase/react-native-firebase#4367]
https://www.youtube.com/watch?v=LYi1gwPWDto
I have followed this video and got this (below) error at ( follow this timestamp link ) npx react-native run-android:
https://youtu.be/LYi1gwPWDto?list=PLsprmdocuVe9SvIQveOWqMvxHdkXjcRO_&t=518

PLEASE HELP ME IT'S URGENT

//Error
D:\0_Online_courses\project_excercize\react-native\React native core\reactnativefirebase>npx react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 895 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...
info Installing the app...

> Configure project :react-native-firebase_app
:react-native-firebase_app:firebase.bom using default value: 24.1.0
:react-native-firebase_app package.json found at D:\0_Online_courses\project_excercize\react-native\React native core\reactnativefirebase\node_modules\@react-native-firebase\app\package.json        
:react-native-firebase_app:version set from package.json: 6.7.1 (6,7,1 - 6007001)
:react-native-firebase_app:android.compileSdk using custom value: 29
:react-native-firebase_app:android.targetSdk using custom value: 29
:react-native-firebase_app:android.minSdk using custom value: 16
:react-native-firebase_app:reactNativeAndroidDir D:\0_Online_courses\project_excercize\react-native\React native core\reactnativefirebase\node_modules\react-native\android

> Task :react-native-firebase_app:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.        
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6/userguide/command_line_interface.html#sec:command_line_warnings    
20 actionable tasks: 2 executed, 18 up-to-date
D:\0_Online_courses\project_excercize\react-native\React native core\reactnativefirebase\node_modules\@react-native-firebase\app\android\src\reactnative\java\io\invertase\firebase\app\ReactNativeFirebaseAppInitProvider.java:25: error: cannot find symbol
    BuildConfig.APPLICATION_ID + ".reactnativefirebaseappinitprovider";
               ^
  symbol:   variable APPLICATION_ID
  location: class BuildConfig
Note: D:\0_Online_courses\project_excercize\react-native\React native core\reactnativefirebase\node_modules\@react-native-firebase\app\android\src\reactnative\java\io\invertase\firebase\utils\ReactNativeFirebaseUtilsModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-firebase_app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more 
log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
D:\0_Online_courses\project_excercize\react-native\React native core\reactnativefirebase\node_modules\@react-native-firebase\app\android\src\reactnative\java\io\invertase\firebase\app\ReactNativeFirebaseAppInitProvider.java:25: error: cannot find symbol
    BuildConfig.APPLICATION_ID + ".reactnativefirebaseappinitprovider";
               ^
  symbol:   variable APPLICATION_ID
  location: class BuildConfig
Note: D:\0_Online_courses\project_excercize\react-native\React native core\reactnativefirebase\node_modules\@react-native-firebase\app\android\src\reactnative\java\io\invertase\firebase\utils\ReactNativeFirebaseUtilsModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-firebase_app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more 
log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

    at checkExecSyncError (child_process.js:621:11)
    at execFileSync (child_process.js:639:15)
    at runOnAllDevices (D:\0_Online_courses\project_excercize\react-native\React native core\reactnativefirebase\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:39)
    at buildAndRun (D:\0_Online_courses\project_excercize\react-native\React native core\reactnativefirebase\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:179:41)
    at D:\0_Online_courses\project_excercize\react-native\React native core\reactnativefirebase\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:133:12   
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.handleAction (D:\0_Online_courses\project_excercize\react-native\React native 
core\reactnativefirebase\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:182:9)

**Comment by mikehardy** [comment]
Hi there!
You ignored the template.

This has been seen before: https://github.com/invertase/react-native-firebase/issues/3254

It was fixed, so I'm guessing if you had included the information requested in the template, we would see that you have old versions of react-native-firebase that are incompatible with Android Studio 4 / android gradle plugin 4.x

Use current stable versions of react-native-firebase and you should be good to go.

**Comment by Chandravardhan8998** [comment]
> Hi there!
> You ignored the template.
> 
> This has been seen before: #3254
> 
> It was fixed, so I'm guessing if you had included the information requested in the template, we would see that you have old versions of react-native-firebase that are incompatible with Android Studio 4 / android gradle plugin 4.x
> 
> Use current stable versions of react-native-firebase and you should be good to go.

I have the latest version of react-native-firebase, react, react-native & android studio

"dependencies": {
    "@react-native-firebase/app": "6.7.1",
    "react": "16.9.0",
    "react-native": "0.61.5"
  },

**Comment by mikehardy** [comment]
False.
react-native is on 0.63.x
react-native-firebase/app is on 8.4.5
react is also higher.

**Comment by jawkhan** [comment]
Hi,

I have this same issue.

I have the latest versions of react-native-firebase/app, react-native and react, but I'm still getting this error comes up.
If I run the app from inside android studio, I don't get this issue. As soon as I use the CLI with the command 
`npx react-native run-android` that's when I get this error.

Please advise.

**Comment by mikehardy** [comment]
This is a closed issue. I typically spend no time on closed issues.

If you can reproduce with https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh then I'm very interested and would appreciate a new issue following the template. If you cannot reproduce with that script then it's a project-specific problem and you can probably find the problem by comparing the result of that script and your local problem
