### ISSUE TITLE
TypeError: (0,_ml.default) is not a function

### ISSUE THREAD

**Issue by scaralfred** [invertase/react-native-firebase#4546]
#4421  Issue

- Installed this package [https://www.npmjs.com/package/@react-native-firebase/ml](https://www.npmjs.com/package/@react-native-firebase/ml) 
- Called this method => ml().cloudDocumentTextRecognizerProcessImage(imagePath)
- Got this error => TypeError: (0,_ml.default) is not a function

This error can be reproduced by simply following the steps on these pages:
- First step => [https://rnfirebase.io/ml/usage](https://rnfirebase.io/ml/usage)
- Second step =>  [https://rnfirebase.io/ml/text-recognition](https://rnfirebase.io/ml/text-recognition)

**Comment by mikehardy** [comment]
Thanks for pointing this out - there was obviously a massive re-shape in the ML packages in this last release, but the E2E tests had pretty good coverage, I'm surprised something like this slipped through. I will investigate later today, though if in the meantime you reach in to node_modules and see something obvious you could beat me to it with a PR 😄

**Comment by mikehardy** [comment]
Sorry I didn't get a chance to investigate this earlier. I still haven't tried the actual reproduction steps (I opted to implement the auth emulator over the last few days, it was a very popular request...)

But we exercise this function right here:

https://github.com/invertase/react-native-firebase/blob/e3ff7bdf3e520b448ac836ab5c59557e2a619752/packages/ml/e2e/documentText.e2e.js#L161-L186

it passes E2E tests on both iOS and Android. So I'm confused. Possibilities: documented integration steps are different than those actually done for our test app used in E2E CI testing, API call style or arguments are different and some assumptions are made about them, project-specific integration issues have happened, and/or the ever-present "something we haven't imagined yet has gone wrong"

**Comment by freefred81** [comment]
hi i have the same error here (on IOS) 

React native vs ~0.63.3

my code:

```
const processDocument = async (localPath: string) => { 
    const processed = await firebase .ml().cloudDocumentTextRecognizerProcessImage(
      localPath
    );

    console.warn("Found text in document: ", processed.text);

    processed.blocks.forEach(
      (block: { text: any; confidence: any; recognizedLanguages: any }) => {
        console.warn("Found block with text: ", block.text);
        console.warn("Confidence in block: ", block.confidence);
        console.warn("Languages found in block: ", block.recognizedLanguages);
      }
    );
  };
```


same error
![IMG_A71DBBEA1104-1](https://user-images.githubusercontent.com/25612263/99406006-affebe80-28ed-11eb-914f-04a7d7f95843.jpeg)

**Comment by scaralfred** [comment]
I solved this by upgrading all the firebase libraries in my project.
Although I think it was enough to upgrade just react-native-firebase/app

**Comment by freefred81** [comment]
I was doing the a same thing!!

Really thnx!

**Comment by mikehardy** [comment]
Whew! I'm glad that worked. I/we understand the versioning is a bit confusing, we went with "independent" versioning for react-native-firebase sub-packages but in the end this is not a great developer experience, the next release (coming out today) will follow the firebase-ios-sdk recent change and start using One True Version so it's more clear that everything matches. We'll burn more version numbers, but those are free, and it won't be confusing

I'm going to close this as getting to current stable on everything should fix it

**Comment by G1914G** [comment]
Hi I have still the same problem and upgraded all the packages.



My Code:

````
async function processDocument(localPath) {
  const processed = await ml().cloudDocumentTextRecognizerProcessImage(localPath);

  console.log('Found text in document: ', processed.text);

  processed.blocks.forEach(block => {
    console.log('Found block with text: ', block.text);
    console.log('Confidence in block: ', block.confidence);
    console.log('Languages found in block: ', block.recognizedLanguages);
  });
}
````

Can you please help me out?

**Comment by mikehardy** [comment]
I cannot, sorry, as mentioned I can't reproduce. We have an E2E test in our CI environment that exercises the method (I think) and it appears to work.

If you can create an App.js that you drop in to an app built from this demo construction script, we might be able to reproduce - you should try it to see if it works in a clean app like that: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by yamila-fraiman** [comment]
same issue, any idea?
