### ISSUE TITLE
🔥[🐛] Failed resolution of: Landroidx/browser/customtabs/CustomTabsIntent$Builder;

### ISSUE THREAD

**Issue by RobertSasak** [invertase/react-native-firebase#4744]
## 🔥Issue

This issue only occurs on Huawei phone when doing phone authentification. Newest Huawei phones does no contain Google Mobile Services. Normaly would phone use GMS to perform check of the user before SMS authentification. Since GMS is not available on the phone there is a fallback solution using Captcha. More info about it is here https://firebase.google.com/docs/auth/android/phone-auth#enable-app-verification

This issue occurs rightt after calling `auth().signInWithPhoneNumber(phoneNumber)`. App is trying to open browser and load captcha website. 

### Solution

As described in https://github.com/firebase/firebase-android-sdk/issues/2164#issuecomment-736777284 solution is to add dependency on browser into build.gradle
```
implementation "androidx.browser:browser:1.2.0"
```

### Question

Should *react-native-firebase* include this dependency on browser? If not please close this issue and keep it as a reference. 

### LogCat
```
2021-01-07 13:25:18.228 25511-25511/xxx E/AndroidRuntime: FATAL EXCEPTION: main
    Process: sk.sasak.norgeskart, PID: 25511
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/browser/customtabs/CustomTabsIntent$Builder;
        at com.google.firebase.auth.internal.RecaptchaActivity.zza(com.google.firebase:firebase-auth@@20.0.1:13)
        at com.google.android.gms.internal.firebase-auth-api.zzth.zzb(com.google.firebase:firebase-auth@@20.0.1:7)
        at com.google.android.gms.internal.firebase-auth-api.zzth.onPostExecute(Unknown Source:2)
        at android.os.AsyncTask.finish(AsyncTask.java:797)
        at android.os.AsyncTask.access$900(AsyncTask.java:195)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:814)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8349)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.browser.customtabs.CustomTabsIntent$Builder" on path: DexPathList[[zip file "/data/app/xxx-gHnlpJrXYA5PszLQfdufZw==/base.apk"],nativeLibraryDirectories=[/data/app/sk.sasak.norgeskart-gHnlpJrXYA5PszLQfdufZw==/lib/arm64, /data/app/sk.sasak.norgeskart-gHnlpJrXYA5PszLQfdufZw==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:209)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.firebase.auth.internal.RecaptchaActivity.zza(com.google.firebase:firebase-auth@@20.0.1:13) 
        at com.google.android.gms.internal.firebase-auth-api.zzth.zzb(com.google.firebase:firebase-auth@@20.0.1:7) 
        at com.google.android.gms.internal.firebase-auth-api.zzth.onPostExecute(Unknown Source:2) 
        at android.os.AsyncTask.finish(AsyncTask.java:797) 
        at android.os.AsyncTask.access$900(AsyncTask.java:195) 
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:814) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:219) 
        at android.app.ActivityThread.main(ActivityThread.java:8349) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055) 
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
        "@react-native-firebase/analytics": "10.4.0",
        "@react-native-firebase/app": "10.4.0",
        "@react-native-firebase/auth": "10.4.0",
        "@react-native-firebase/crashlytics": "10.4.0",
        "@react-native-firebase/firestore": "10.4.0",
        "@react-native-firebase/remote-config": "10.4.0",
}
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [X] my application is an AndroidX application?
- [X] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [X] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 19
        compileSdkVersion = 29
        targetSdkVersion = 29
    }
    repositories {
        google()
        jcenter()
        maven { url 'http://developer.huawei.com/repo/' }
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.3")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        
        // Needed by Firebase
        classpath 'com.google.gms:google-services:4.2.0'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'
        // Huawei
        classpath 'com.huawei.agconnect:agcp:1.3.1.300'
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
        maven { url 'https://developer.huawei.com/repo/' } 
    }
}

```

#### `android/app/build.gradle`:

```groovy
apply plugin: "com.android.application"
apply plugin: 'com.huawei.agconnect'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation. If none specified and
 *   // "index.android.js" exists, it will be used. Otherwise "index.js" is
 *   // default. Can be overridden with ENTRY_FILE environment variable.
 *   entryFile: "index.android.js",
 *
 *   // https://facebook.github.io/react-native/docs/performance#enable-the-ram-format
 *   bundleCommand: "ram-bundle",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    enableHermes: true,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        resConfigs "en"
        applicationId "xxx"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 4
        versionName "4"
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner' // Fastlane screenshots
        multiDexEnabled true
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        release {
        }
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }

    packagingOptions {
        pickFirst "lib/armeabi-v7a/libc++_shared.so"
        pickFirst "lib/arm64-v8a/libc++_shared.so"
        pickFirst "lib/x86/libc++_shared.so"
        pickFirst "lib/x86_64/libc++_shared.so"
    }

    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules

    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }

    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
    
    //multidex
    def multidex_version = "2.0.1"
    implementation 'androidx.multidex:multidex:$multidex_version'

    // Fastlane screenshots
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0-alpha03'
    androidTestImplementation 'androidx.test:rules:1.3.0-alpha03'
    androidTestImplementation 'tools.fastlane:screengrab:2.0.0'

    // Huawei
    implementation 'com.huawei.hms:iap:4.0.4.300'
    implementation 'com.huawei.agconnect:agconnect-core:1.3.1.300'
    
    // https://github.com/invertase/react-native-firebase/issues/4744 
    implementation "androidx.browser:browser:1.2.0"
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

project.ext.vectoricons = [
    iconFontNames: [ 'MaterialCommunityIcons.ttf' ] // Name of the font files you want to copy
]

apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

// Needed by firebase
apply plugin: 'com.google.gms.google-services'
```

#### `android/settings.gradle`:

```groovy
rootProject.name = '@react-native-firebase_analytics'
```

#### `MainApplication.java`:

```java
package xxx;

import android.app.Application;
import android.content.Context;
import android.database.sqlite.SQLiteDatabase;

import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.afrihost.hms.hashms.HasHmsPackage;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;
import java.lang.reflect.InvocationTargetException;
import java.util.List;

// Multidex support
import androidx.multidex.MultiDexApplication;

public class MainApplication extends MultiDexApplication implements ReactApplication {

  private final ReactNativeHost mReactNativeHost =
      new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());
          return packages;
        }

        @Override
        protected String getJSMainModuleName() {
          return "index";
        }
      };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
  }

  /**
   * Loads Flipper in React Native templates. Call this in the onCreate method with something like
   * initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
   *
   * @param context
   * @param reactInstanceManager
   */
  private static void initializeFlipper(
      Context context, ReactInstanceManager reactInstanceManager) {
    if (BuildConfig.DEBUG) {
      try {
        /*
         We use reflection here to pick up the class that initializes Flipper,
        since Flipper library is not available in release mode
        */
        Class<?> aClass = Class.forName("xxx.ReactNativeFlipper");
        aClass
            .getMethod("initializeFlipper", Context.class, ReactInstanceManager.class)
            .invoke(null, context, reactInstanceManager);
      } catch (ClassNotFoundException e) {
        e.printStackTrace();
      } catch (NoSuchMethodException e) {
        e.printStackTrace();
      } catch (IllegalAccessException e) {
        e.printStackTrace();
      } catch (InvocationTargetException e) {
        e.printStackTrace();
      }
    }
  }
}

```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
info Fetching system and libraries information...
(node:16355) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 11.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 76.63 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.4.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.15 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
    Python: 3.7.6 - /Users/robert/opt/miniconda3/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [X] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `10.4.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Auth`
- **Are you using `TypeScript`?**
  - `Y` & `4.1.3`

</p>
</details>

**Comment by mikehardy** [comment]
Interesting, you did not provide any android build.gradle details so I can't see if you've overridden firebase-android-sdk BoM version. 

If you have not overridden it and the package.json snippet you included (with react-native-firebase 10.4.0) is accurate then you are on current release of firebase-android-sdk, i.e. 26.2.0

https://github.com/invertase/react-native-firebase/blob/a8dcd54d8a7d49e3da05da9ddcfdd6abd976bb48/packages/app/package.json#L72

Can you confirm that is the case, that you are on firebase-android-sdk 26.2.0?

If you are on 26.2.0 and still reproduce this, the upstream issue needs a reopen and a fix, and we may issue a workaround here. If you are not on 26.2.0 please update to do that and check if it fixes it or not and go from there

**Comment by RobertSasak** [comment]
I included more android files. I am not aware of any override. I am not sure what is BoM version. 

Here is trimmed output of all dependencies. As far I can see I am using 26.2.0 version. I somehow believe that I am just doing something wrong, since it was already fixed upstream. 
```
$ ./gradlew app:dependencies
```
```
...
> Configure project :react-native-firebase_analytics
:react-native-firebase_analytics package.json found at /Users/robert/Documents/Bitbucket/xxx/node_modules/@react-native-firebase/analytics/package.json
:react-native-firebase_app package.json found at /Users/robert/Documents/Bitbucket/xxx/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_analytics:firebase.bom using default value: 26.2.0
:react-native-firebase_analytics package.json found at /Users/robert/Documents/Bitbucket/xxx/node_modules/@react-native-firebase/analytics/package.json
:react-native-firebase_analytics:version set from package.json: 10.4.0 (10,4,0 - 10004000)
:react-native-firebase_analytics:android.compileSdk using custom value: 29
:react-native-firebase_analytics:android.targetSdk using custom value: 29
:react-native-firebase_analytics:android.minSdk using custom value: 19
:react-native-firebase_analytics:reactNativeAndroidDir /Users/robert/Documents/Bitbucket/xxx/node_modules/react-native/android

> Configure project :react-native-firebase_app
:react-native-firebase_app package.json found at /Users/robert/Documents/Bitbucket/xxx/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_app:firebase.bom using default value: 26.2.0
:react-native-firebase_app:play.play-services-auth using default value: 19.0.0
:react-native-firebase_app package.json found at /Users/robert/Documents/Bitbucket/xxx/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_app:version set from package.json: 10.4.0 (10,4,0 - 10004000)
:react-native-firebase_app:android.compileSdk using custom value: 29
:react-native-firebase_app:android.targetSdk using custom value: 29
:react-native-firebase_app:android.minSdk using custom value: 19
:react-native-firebase_app:reactNativeAndroidDir /Users/robert/Documents/Bitbucket/xxx/node_modules/react-native/android

> Configure project :react-native-firebase_auth
:react-native-firebase_auth package.json found at /Users/robert/Documents/Bitbucket/xxx/node_modules/@react-native-firebase/auth/package.json
:react-native-firebase_app package.json found at /Users/robert/Documents/Bitbucket/xxx/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_auth:firebase.bom using default value: 26.2.0
:react-native-firebase_auth package.json found at /Users/robert/Documents/Bitbucket/xxx/node_modules/@react-native-firebase/auth/package.json
:react-native-firebase_auth:version set from package.json: 10.4.0 (10,4,0 - 10004000)
:react-native-firebase_auth:android.compileSdk using custom value: 29
:react-native-firebase_auth:android.targetSdk using custom value: 29
:react-native-firebase_auth:android.minSdk using custom value: 19
:react-native-firebase_auth:reactNativeAndroidDir /Users/robert/Documents/Bitbucket/xxx/node_modules/react-native/androi
...
```

**Comment by mikehardy** [comment]
Cool - thanks for showing that. You are using 26.2.0 so this is still an issue. It wasn't fixed upstream, it was just closed for lack of activity. It appears it should be reopened. I'll head over there and see what I can do.

We may work around it here but in the meantime you will definitely need the dependency in your project it seems

**Comment by RobertSasak** [comment]
Thank you for such a quick response. As there is a simple workaround, there is no need for any imediate action. We can wait until it is fixed upstream. Let me me know if I can be any help and thank you for your amazing work.

**Comment by SoLoHK525** [comment]
I am having the same issue running on AVDs

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.projectca, PID: 25815
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/browser/customtabs/CustomTabsIntent$Builder;
        at com.google.firebase.auth.internal.RecaptchaActivity.zza(com.google.firebase:firebase-auth@@20.0.1:13)
        at com.google.android.gms.internal.firebase-auth-api.zzth.zzb(com.google.firebase:firebase-auth@@20.0.1:7)
        at com.google.android.gms.internal.firebase-auth-api.zzth.onPostExecute(Unknown Source:2)
        at android.os.AsyncTask.finish(AsyncTask.java:771)
        at android.os.AsyncTask.access$900(AsyncTask.java:199)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.browser.customtabs.CustomTabsIntent$Builder" on path: DexPathList[[zip file "/data/app/~~xssj6JVkLUUVF8ClzzhARQ==/com.projectca-wz-ZDu8GHCZfvg1E3_3mVw==/base.apk"],nativeLibraryDirectories=[/data/app/~~xssj6JVkLUUVF8ClzzhARQ==/com.projectca-wz-ZDu8GHCZfvg1E3_3mVw==/lib/x86, /data/app/~~xssj6JVkLUUVF8ClzzhARQ==/com.projectca-wz-ZDu8GHCZfvg1E3_3mVw==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.firebase.auth.internal.RecaptchaActivity.zza(com.google.firebase:firebase-auth@@20.0.1:13) 
        at com.google.android.gms.internal.firebase-auth-api.zzth.zzb(com.google.firebase:firebase-auth@@20.0.1:7) 
        at com.google.android.gms.internal.firebase-auth-api.zzth.onPostExecute(Unknown Source:2) 
        at android.os.AsyncTask.finish(AsyncTask.java:771) 
        at android.os.AsyncTask.access$900(AsyncTask.java:199) 
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) `

**Comment by mikehardy** [comment]
@SoLoHK525 it can happen anytime for a variety of reasons. Showing the web recaptcha flow is the standard backup flow for authentication. If the workaround works for you, you're all set.

**Comment by mikehardy** [comment]
We would love a PR to enable the setting of the new toggle which forces the ReCAPTCHA flow actually:

https://rnfirebase.io/reference/auth/authsettings is the settings object in react-native-firebase that wraps
https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuthSettings

which now has:
https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuthSettings#public-abstract-void-forcerecaptchaflowfortesting-boolean-forcerecaptchaflow

as of November / android BoM 26.1.0 https://firebase.google.com/support/release-notes/android#auth_v20-0-1

Then you can check this easily, any time

**Comment by mikehardy** [comment]
In v10.6.4 I have shipped a workaround that includes the androidx.browser dependency:

- with gradle version constraints of "anything from version 1 up through but not including version 2"
- with a version override possible via "androidxBrowserVersion" in the `ext` configuration block of `android/build.gradle`

...so this should not crash anyone anymore

I'm going to leave this open though, as it is an upstream bug and a workaround is not the same as a fix.

**Comment by mikehardy** [comment]
Just waiting on

> the next release that Auth is a part of.

https://github.com/firebase/firebase-android-sdk/issues/2164#issuecomment-809605370

**Comment by mikehardy** [comment]
I can see it resolving correctly now in react-native-firebase v12.0.0 via `./gradlew :app:dependencies`:

```

+--- project :react-native-firebase_auth
|    +--- project :react-native-firebase_app (*)
|    +--- com.facebook.react:react-native:+ -> 0.64.1 (*)
|    +--- com.google.firebase:firebase-bom:28.0.1 (*)
|    +--- com.google.firebase:firebase-auth -> 21.0.1
|    |    +--- androidx.browser:browser:1.0.0
```

Closable! Will remove the workaround
