### ISSUE TITLE
[🐛] [messaging/unregistered] after messaging().registerDeviceForRemoteMessages() on iOS 16.2

### ISSUE THREAD

**Issue by antonandreyev** [invertase/react-native-firebase#6829]
## Issue

After `messaging().registerDeviceForRemoteMessages()` use of `messaging().getToken()` is still throwing `[messaging/unregistered] You must be registered for remote messages before calling getToken, see messaging().registerDeviceForRemoteMessages()` on iOS 16.2. Probably some older or newer versions are also affected, but not visible in my logs at the moment. If more logs will come I will update the issue.

Code is simple:
```
messaging()
  .registerDeviceForRemoteMessages() // no-op on Android and if already registered
  .then(() => messaging().getToken())
  .then((t) => {
    setToken(t);
    setIsInitialized(true);
  }) 
```

UPD:
> To clarify about my case: that didn't came overnight. We started to notice this "need to register" error a while ago. We thought we could fix that with explicitly registering and changed code to that is in the opening message. But that didn't help and now we see both "no need to register" and "you need to register". The case is quite rare though.

Using Sentry, here are some extractions from logs:
- devices: iPhone11,8, iPhone 15.2. All with iOS 16.2
- example of the log (UPD: read bottom to top):
![image](https://user-images.githubusercontent.com/5842508/211752849-a7f88847-3fe8-4dea-a105-1c70e663b67a.png)

UPD: Sentry statistics for 48 hours:
- 22k users in total
- 69k user sessions in total
- 10 users with this error
- 526 errors of this kind
- devices: iPhone12,1, iPhone14,3, iPhone11,8, iPhone15,2, iPhone11,6, iPhone13,4
- OS: 15.6.1, 16.1.1, 16.1.2, 16.2
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "...",
  "version": "0.1.0",
  "license": "UNLICENSED",
  "main": "index.js",
  "private": true,
  "engineStrict": true,
  "engines": {
    "node": "16.19.0",
    "yarn": "1.22.17"
  },
  "scripts": {
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start --reset-cache",
    "start-cached": "react-native start",
    "lint": "eslint . --ext .tsx,.ts",
    "lint:fix": "yarn lint --fix",
    "tsc": "tsc",
    "test": "jest",
    "test:ci": "jest --passWithNoTests --ci",
    "codegen": "graphql-codegen",
    "translation:gen": "ts-node scripts/fetch-static-translations.ts && prettier --write src/__resources__/i18n_resource.json",
    "prettier": "prettier --check './src/**/*.{ts,tsx,json}'",
    "prettier:fix": "prettier --write './**/*.{ts,tsx,json}'",
    "prepare": "husky install",
    "ci": "rm -rf node_modules && yarn install --prefer-offline --frozen-lockfile && yarn cache clean",
    "postinstall": "patch-package",
    "ios:test": "yarn detox test --configuration ios.debug",
    "ios:build": "yarn detox build --configuration ios.debug",
    "e2e:ios": "yarn ios:build && yarn ios:test",
    "android:test": "yarn detox test --configuration android",
    "android:build": "yarn detox build --configuration android",
    "e2e:android": "yarn android:build && yarn android:test"
  },
  "dependencies": {
    "@apollo/client": "^3.7.3",
    "@formatjs/intl-getcanonicallocales": "^2.0.5",
    "@formatjs/intl-locale": "^3.0.11",
    "@formatjs/intl-numberformat": "^8.3.3",
    "@formatjs/intl-pluralrules": "^5.1.8",
    "@gorhom/bottom-sheet": "~4.4.5",
    "@react-native-async-storage/async-storage": "~1.17.11",
    "@react-native-clipboard/clipboard": "^1.11.1",
    "@react-native-community/art": "^1.2.0",
    "@react-native-firebase/analytics": "^16.4.6",
    "@react-native-firebase/app": "~16.4.6",
    "@react-native-firebase/messaging": "^16.4.6",
    "@react-native-masked-view/masked-view": "^0.2.8",
    "@react-navigation/bottom-tabs": "6.5.0",
    "@react-navigation/native": "6.1.0",
    "@react-navigation/stack": "6.3.8",
    "@sentry/react-native": "4.2.2",
    "accordion-collapse-react-native": "^1.1.1",
    "d3-scale": "^4.0.2",
    "date-fns": "^2.29.3",
    "date-fns-tz": "^1.3.7",
    "expo": "~46.0.17",
    "expo-av": "~12.0.4",
    "expo-constants": "~13.2.4",
    "expo-device": "~4.3.0",
    "expo-file-system": "~14.1.0",
    "expo-font": "~10.2.0",
    "expo-network": "~4.3.0",
    "expo-secure-store": "~11.3.0",
    "expo-splash-screen": "~0.16.2",
    "expo-updates": "~0.14.7",
    "expo-web-browser": "~11.0.0",
    "formik": "^2.2.9",
    "graphql": "^16.6.0",
    "i18next": "^22.4.9",
    "jwt-decode": "^3.1.2",
    "lodash": "^4.17.21",
    "lottie-react-native": "~5.1.3",
    "luxon": "^3.2.1",
    "react": "18.0.0",
    "react-apollo-network-status": "^5.2.1",
    "react-dom": "18.0.0",
    "react-i18next": "^12.1.4",
    "react-native": "0.69.7",
    "react-native-animatable": "^1.3.3",
    "react-native-calendars": "^1.1293.0",
    "react-native-device-info": "^10.3.0",
    "react-native-gesture-handler": "^2.8.0",
    "react-native-indicators": "^0.17.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-localize": "^2.2.4",
    "react-native-media-query": "^2.0.0",
    "react-native-reanimated": "~2.13.0",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2",
    "react-native-share": "^8.0.0",
    "react-native-skeleton-placeholder": "5.2.4",
    "react-native-svg": "^13.6.0",
    "react-native-url-polyfill": "^1.3.0",
    "react-native-view-pdf": "^0.14.0",
    "sentry-expo": "^5.0.3",
    "styled-components": "~5.3.6",
    "victory-core": "~36.6.8",
    "victory-native": "~36.6.8",
    "victory-tooltip": "~36.6.8",
    "yup": "^0.32.11",
    "zod": "^3.20.2"
  },
  "devDependencies": {
    "@babel/core": "~7.20.12",
    "@babel/plugin-syntax-flow": "^7.18.6",
    "@babel/plugin-transform-react-jsx": "^7.20.7",
    "@babel/preset-typescript": "~7.18.6",
    "@expo/config": "^7.0.3",
    "@graphql-codegen/cli": "^2.16.3",
    "@graphql-codegen/near-operation-file-preset": "^2.5.0",
    "@graphql-codegen/schema-ast": "^2.6.1",
    "@graphql-codegen/typescript-operations": "^2.5.12",
    "@graphql-codegen/typescript-react-apollo": "~3.3.7",
    "@testing-library/react-native": "^10.1.1",
    "@tsconfig/node16": "^1.0.3",
    "@types/d3-scale": "^4.0.3",
    "@types/jest": "^27.5.2",
    "@types/luxon": "^3.2.0",
    "@types/node": "^17.0.45",
    "@types/react": "~18.0.26",
    "@types/react-native": "~0.69.16",
    "@types/xml2js": "^0.4.11",
    "@typescript-eslint/eslint-plugin": "^5.48.1",
    "@typescript-eslint/parser": "^5.48.1",
    "@xtrctio/eslint-plugin-disallow-date": "^1.0.1",
    "babel-preset-expo": "^9.2.2",
    "cross-fetch": "^3.1.5",
    "detox": "^20.1.1",
    "eslint": "^8.31.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-prettier": "^8.6.0",
    "eslint-config-react-app": "^7.0.1",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jsx-a11y": "^6.7.0",
    "eslint-plugin-react": "^7.31.11",
    "eslint-plugin-react-hooks": "^4.3.0",
    "expo-cli": "^6.0.8",
    "graphql-tag": "^2.12.6",
    "husky": "^8.0.3",
    "import-sort-style-eslint": "^6.0.0",
    "jest": "27.5.1",
    "jest-junit": "^15.0.0",
    "lint-staged": "^13.1.0",
    "patch-package": "^6.5.1",
    "prettier": "2.8.2",
    "prettier-plugin-import-sort": "^0.0.7",
    "react-native-dotenv": "^3.4.6",
    "react-test-renderer": "18.0.0",
    "ts-node": "^10.9.1",
    "typescript": "~4.9.4"
  },
  "importSort": {
    ".js, .jsx, .ts, .tsx": {
      "style": "eslint",
      "parser": "typescript"
    }
  },
  "lint-staged": {
    "**/*.ts?(x)": [
      "eslint",
      "prettier --write"
    ]
  }
}
```

#### `firebase.json` for react-native-firebase v6:
(no firebase.json)
```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

production = ENV["PRODUCTION"] == "1"

require 'json'
podfile_properties = JSON.parse(File.read('./Podfile.properties.json')) rescue {}

target '...' do
  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  config = use_native_modules!
  config = use_frameworks! :linkage => :static

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config["reactNativePath"],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == 'hermes',
    :production => production,
    :fabric_enabled => flags[:fabric_enabled],
    # disable due to use_frameworks needed by firebase
    :flipper_configuration => FlipperConfiguration.disabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'Firebase/Analytics'

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <React/RCTLinkingManager.h>
#import <React/RCTConvert.h>
#import <React/RCTAppSetupUtils.h>
#import <Firebase.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  RCTAppSetupPrepareApp(application);

  [FIRApp configure];

  RCTBridge *bridge = [self.reactDelegate createBridgeWithDelegate:self launchOptions:launchOptions];

  NSDictionary *initProps = [self prepareInitialProps];
  UIView *rootView = [self.reactDelegate createRootViewWithBridge:bridge moduleName:@"main" initialProperties:nil];

  if (@available(iOS 13.0, *)) {
      rootView.backgroundColor = [UIColor systemBackgroundColor];
  } else {
      rootView.backgroundColor = [UIColor whiteColor];
  }

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [self.reactDelegate createRootViewController];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  [super application:application didFinishLaunchingWithOptions:launchOptions];

  return YES;
}

- (NSDictionary *)prepareInitialProps
{
  NSMutableDictionary *initProps = [NSMutableDictionary new];
  return initProps;
}

- (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge
{
  // If you'd like to export some custom RCTBridgeModules that are not Expo modules, add them here!
  return @[];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge {
 #ifdef DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
 #else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
 #endif
}

// Linking API
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  return [super application:application openURL:url options:options] || [RCTLinkingManager application:application openURL:url options:options];
}

// Universal Links
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler {
  BOOL result = [RCTLinkingManager application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
  return [super application:application continueUserActivity:userActivity restorationHandler:restorationHandler] || result;
}

// Explicitly define remote notification delegates to ensure compatibility with some third-party libraries
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
  return [super application:application didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}

// Explicitly define remote notification delegates to ensure compatibility with some third-party libraries
- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error
{
  return [super application:application didFailToRegisterForRemoteNotificationsWithError:error];
}

// Explicitly define remote notification delegates to ensure compatibility with some third-party libraries
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler
{
  return [super application:application didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}

@end

```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

N/A

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 9.29 GB / 31.68 GB
  Binaries:
    Node: 16.19.0 - C:\Users\ANTON~1.AND\AppData\Local\Temp\yarn--1673424499379-0.7430549663942487\node.CMD
    Yarn: 1.22.17 - C:\Users\ANTON~1.AND\AppData\Local\Temp\yarn--1673424499379-0.7430549663942487\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 27, 30, 31, 33
      Build Tools: 27.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64       
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 11.0.15
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.7 => 0.69.7
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [X] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `16.4.6`
- **`Firebase` module(s) you're using that has the issue:**
  - `messaging`
- **Are you using `TypeScript`?**
  - `Y` & `4.9.4`

</p>
</details>

---

**Comment by tomwanzek** [comment]
@livnunes @antonandreyev Your experience replicates for me iPhone 14 (iOS 16.0) emulator, since this morning, I'm getting the exact same error:
> NativeFirebaseError: [messaging/unknown] The operation couldn’t be completed. Invalid fetch response, expected 'token' or 'Error' key

There have been no Firebase-related library changes in our RN project in the time frame in question. I did how ever run a fresh pod install this morning as part of some unrelated 3rd party library changes. Podfile.lock is unchanged w.r.t. Firebase.

For what it's worth the project is on RN 0.68.5 with RN Firebase 13.0.1.

We were in the process of looking into the RN Firebase upgrade, but need to complete our assessment of the breaking change with `use_frameworks!` in RN Firebase 15.

**Comment by tomwanzek** [comment]
Currently we can not replicate it in STAGING or PROD, but if this is due to some "unpinned" deep dependency that gets updated to a disfunctional/incompatible native library with the next Deployment CI run, we would have a real 🔥.

The bug stops the App cold when the user logs in, and we try to `getToken()`.

**Comment by tomwanzek** [comment]
@mikehardy By any chance, are you aware of anything that might have caused this sudden change "overnight"? 🙇

**Comment by antonandreyev** [comment]
To clarify about my case: that didn't came overnight. We started to notice this "need to register" error a while ago. The thought we could fix that with explicitely registering and changed to that is in the opening message. But that didn't help and now we see both "no need to register" and "you need to register". The case is quite rare though, 100 errors in 10000 sessions in past 24 hours.

**Comment by tomwanzek** [comment]
@antonandreyev Thanks for the clarification and in order to keep your issue what it was meant to be, I have opened: https://github.com/invertase/react-native-firebase/issues/6830 cc @livnunes @mikehardy

**Comment by rivaros** [comment]
Hello, the above issue could happen because of unresolved issue https://github.com/invertase/react-native-firebase/issues/5377

Please check your Podfile and if you have `abstract_target` there -> that's the case. It does not add `[RNFB] Core Configuration` script phaze.

**Comment by antonandreyev** [comment]
@rivaros the Podfile is attached to the issue and there is no `abstract_target` in it. Also this issue is happening only to a minority of users, so I doubt this is a linking issue. 

It seems much more like the actual issue is that the token fails to be fetched or firebase/messaging fails to be registered in some special cases and the error message is misleading.

**Comment by rivaros** [comment]
@antonandreyev did not notice you included Podfile. So yes, indeed in your case its different.

Have noticed that you implemented `didRegisterForRemoteNotificationsWithDeviceToken`. Does it play well with swizzling https://firebase.google.com/docs/cloud-messaging/ios/client#token-swizzle-disabled ?

**Comment by antonandreyev** [comment]
@rivaros it does. My implementation is just a part of expo setup instructions. As I understand when swizzling is enabled (default) there is no need to change anything in `didRegisterForRemoteNotificationsWithDeviceToken`. At least it does work well as per our monitoring.

**Comment by dragoshuniq** [comment]
Same problem here, any solutions so far ? I'm using React  Native CLI.

` await messaging().registerDeviceForRemoteMessages();` i got this error:

>  Usage of "messaging().registerDeviceForRemoteMessages()" is not required. You only need to register if auto-registration is disabled in your 'firebase.json' configuration file via the 'messaging_ios_auto_register_for_remote_messages' property.

if I remove registerDeviceForRemoteMessage

I got next error:

> [Error: [messaging/unregistered] You must be registered for remote messages before calling getToken, see messaging().registerDeviceForRemoteMessages().]

**Comment by mikehardy** [comment]
@dragoshuniq one is a warning ("that it may not be necessary"), and one is an error ("you are not registered"). There are a few cases where you do actually not need to register, for example if you have AppDelegate swizzling disabled for firebase FCM or similar, and it appears you have one of them for whatever reason.

So, leave that call in.

**Comment by idlework** [comment]
Our user experience the same issue. It only occurs to a small group of users.

Sentry information:
```
device iPhone 11 Pro
device.family iOS
event.environment javascript
event.origin javascript
hermes true
os iOS 16.2
Message error_register_device with message: [messaging/unregistered] You must be registered for remote messages before calling getToken, see messaging().registerDeviceForRemoteMessages().
```

**Comment by mikehardy** [comment]
@idlework that is a legitimate error case that must be handled now with the new strict requirement that you must have an APNS token before getting an FCM token. I am not 100% sure how many cases there are were registration for remote notifications can fail, but it is clearly possible. Perhaps a network error and a retry would work. Perhaps there is a permissions denial by the user? I'm not sure. But, if you cannot get an APNS token, an FCM token is by definition useless and those types of FCM tokens are not issued now, so this error should be handled with some messaging to the user (for example "such and such feature of our app relies on remote notifications and there was an error registering for remote notificaitons. Perhaps check such and such ...")

**Comment by idlework** [comment]
@mikehardy Thanks for the quick and clear answer. I'll implement a check to see what the user response is for the notifications request.

**Comment by marcfrankel** [comment]
@mikehardy It might be worth chiming in that after upgrading to 17.3.1 we started getting the `You must be registered for remote messages before calling getToken, see messaging().registerDeviceForRemoteMessages()` error despite calling it in this order

```
await messaging.registerDeviceForRemoteMessages();
const token = await messaging.getToken();
```

But it was actually due to it being called on an iOS *SIMULATOR*. It might be worth noting somewhere that the new changes around this stuff seem to make simulators throw this error now. The same exact code works fine on physical devices for us.

**Comment by mikehardy** [comment]
Simulators on intel Macs will need to call setAPNSToken now, as there is no token available for them, they do not support APNS or FCM (thus, the error is real). You can set a bogus token in though, we do that for our testing purposes and confirmed via collaboration with firebase-ios-sdk this is a valid strategy: https://github.com/invertase/react-native-firebase/blob/00185a37bc554f9bcb6feb6434d6c9c75ed51a3a/packages/messaging/e2e/messaging.e2e.js#L203

Cool (in my opinion) news though: on M1 macs using latest macOS (ventura) and iOS (in simulator) the Simulator actually supports FCM/APNS - so it works! I tested that personally and cleaned out all the stuff in our code here to enable it.

Both of those things could be called out in the docs more strongly yes - if you remember what page you were on when you were referring to this documentation and got hung up, you might be the best person as I've lost all perspective - there's an edit button at the top of each page and github web UI for docs PRs is just a 1-2 minute thing. I'll shepherd it through

**Comment by marcfrankel** [comment]
@mikehardy I don't think there was a particular page on the documentation, but if it's not too late I'd just add a line to the break change notice in the release notes. I was simply following that when I came across this issue. So perhaps just one line that even if you call registerDeviceForRemoteMessages before getToken it will still fail on intel simulators?

**Comment by LuongTruong** [comment]
Hello @mikehardy , I got the same issue, just upgrade my react native to the latest:
- "react": "18.2.0",
- "react-native": "0.71.4",
- "@react-native-firebase/app": "17.3.2",
- "@react-native-firebase/messaging": "17.3.2",

**Comment by mikehardy** [comment]
@LuongTruong there are quite a few things ("issues") discussed, could you be more specific by including the actual message contents you receive, along with a minimal reproduction that would show the error if placed in an App.js? Do make sure that you have requested + received notification permission from the user, have the correct entitlements, are in an environment where you can either get an APNS token (real device, or current simulator on current macOS on Apple Silicon machine) or you have set an APNS token

**Comment by LuongTruong** [comment]
Hello @mikehardy , thank you for the clear response. Actually, the warning I receive is:

`
You must be registered for remote messages before calling getToken, see messaging().registerDeviceForRemoteMessages().
NativeFirebaseError: [messaging/unregistered] You must be registered for remote messages before calling getToken, see messaging().registerDeviceForRemoteMessages().
`

It is working good with the version:
* "react": "17.0.2",
* "react-native": "0.67.4",
* "@react-native-firebase/app": "16.5.0",
* "@react-native-firebase/messaging": "16.5.0",

"Do make sure that you have requested + received notification permission from the user"
Yes, I did

"have the correct entitlements"
Yes, the app works good before, and I make no changes to the entitlements

"you have set an APNS token"
Yes, I did

But after I upgrade the react-native version and react-native-firebase, the warning appears.

FYI, it looks like the error only appear on the iOS simulator. I tried the real device and it is working good.

**Comment by mikehardy** [comment]
Hmm that is odd - we test on the simulator as our main e2e test environment. It is an x86 simulator though so now follows a different code path from M1-mac+ios16 simulators though since those may receive real APNS tokens and cloud messaging now. You might triple check that you really are registering for remote notifications with no error returned. As I was implementing the new simulator capability of receiving FCM on M1-mac+ios16 I was testing it on simulator all the time and it definitely *can* work.

**Comment by LuongTruong** [comment]
Hello @mikehardy , thank you for the comment and sorry for the late reply.

Actually, my Mac is using the Intel Chip. Below is the code I use to get FCM token

```
async setupFCM(receivedPush: (title: string, body: string) => void): Promise<void> {
  const granted = await messaging().requestPermission();

  if (granted) {
    logPush('granted messaging permissions!');

    messaging().onNotificationOpenedApp(() => {
      // Do something when app receive notification
    });

    logPush('Registered Device For Remote Messages');

    const fcmToken = await messaging().getToken();

    logPush('FCM Token ' + fcmToken);

    // Save FCM token

    messaging().onMessage(remoteMessage => {
      logPush('FCM Message:' + remoteMessage);
      receivedPush(remoteMessage?.data?.title || 'Message', remoteMessage?.data?.body || 'You have a new message');
    });
  } else {
    logPush('User declined messaging permissions');
  }
},
```

Please let me know if you see anything weird in my code. Many thanks!

**Comment by mikehardy** [comment]
You fall into this case I believe:

> Simulators on intel Macs will need to call setAPNSToken now

**Comment by mk04366** [comment]
Still facing this issue. Any fix?

**Comment by asRizvi888** [comment]
Any fix yet?

**Comment by Barney4242** [comment]
I experience this issue on iOS 14.5 device simulator. And the same code works fine on iOS 16.4 device simulator.

**Comment by JestemTrzcinska** [comment]
> I experience this issue on iOS 14.5 device simulator. And the same code works fine on iOS 16.4 device simulator.

Same here. Works perfect on 16.2 iOS Simulator 16.2, but the error occurs in 13.7 iOS Simulator device.

**Comment by Alex1899** [comment]
I am getting this error as well.  IOS Simulator 16.4, M2 mac. 

Once I remove `await messaging().registerDeviceForRemoteMessages();` it throws another warning saying device must be registered for remote messages

**Comment by kartavyaparekh96** [comment]
Is there any success? I waiting from last month

**Comment by Jamal-ReachFirst** [comment]
same issue on iOS simulator

**Comment by luanamarquesf** [comment]
Same here

**Comment by Jailawi** [comment]
Same here, still experiencing this error with intel mac, tried with getAPNSToken() and setAPNSToken(), not working. @mikehardy

**Comment by feuermeister** [comment]
I'm facing the same issue.

**Comment by hanafnafs** [comment]
Any updates regarding this issue?

**Comment by Jailawi** [comment]
Solved it by joining Apple Developer Program, enabling notification capability and registering APN key. I believe most people who are facing this issue are not members of the Apple Developer Program.

**Comment by JordanRichards-hx** [comment]
This is happening for me as well. The `getToken` call successfully executes, it still errors. What's interesting is that it only errors on a real device. Awaiting `messaging().registerDeviceForRemoteMessages().]` before calling `getToken` does not resolve the error.

**Comment by zahid502** [comment]
> @mikehardy It might be worth chiming in that after upgrading to 17.3.1 we started getting the `You must be registered for remote messages before calling getToken, see messaging().registerDeviceForRemoteMessages()` error despite calling it in this order
> 
> ```
> await messaging.registerDeviceForRemoteMessages();
> const token = await messaging.getToken();
> ```
> 
> But it was actually due to it being called on an iOS _SIMULATOR_. It might be worth noting somewhere that the new changes around this stuff seem to make simulators throw this error now. The same exact code works fine on physical devices for us.

It's worked for my side.
@marcfrankel Thanks for the quick and clear answer.

**Comment by feuermeister** [comment]
> This is happening for me as well. The `getToken` call successfully executes in that it still generates a token, but it is triggering an error which is bloating our error reporting. (so we've had to add an ignore case for now)
> 
> What's interesting is that the `...You must be registered...` error only occurs on a real device. Awaiting `messaging().registerDeviceForRemoteMessages().]` before calling `getToken` does not resolve the error, but it does cause a new warning like others have mentioned.

Hm, I see this error on both real devices and emulators. Tried with two iOS versions on real devices, 15.7 and 16.5. Both showing the same warning and no token is being generated. My react-native-firebase version is 17.4.3 and it works like a charm on Android devices. It's very frustrating that no one gave any insight on this bug since it's being created. @antonandreyev , did you managed to fix this issue on your side?

**Comment by antonandreyev** [comment]
@feuermeister no, still happening. At the moment we're just ignoring the error message since it's happening only to a minority of users and nobody yet complained. Need to mention, that we're still on 16.x, can't say anything about latest version.

**Comment by feuermeister** [comment]
https://rnfirebase.io/messaging/usage/ios-setup Seems like there are some additional configurations needed for iOS. Since I haven't enrolled for the developer program yet, I can not tell if this can fix the issue. Have anyone tried going through the process? If not, I'll be able to test in a few days.

**Comment by Yandamuri** [comment]
> https://rnfirebase.io/messaging/usage/ios-setup Seems like there are some additional configurations needed for iOS. Since I haven't enrolled for the developer program yet, I can not tell if this can fix the issue. Have anyone tried going through the process? If not, I'll be able to test in a few days.
> 
> Edit: I also found that some of the info is bit outdated, so instead of searching for "Push notifications" capability, you should select "Background Modes" and then check "Background fetch" and "Remote notifications" <img alt="image" width="461" src="https://user-images.githubusercontent.com/134609463/243170490-c8ec4943-63e9-4868-8cbf-019a5809b825.png">

This configuration resolved my issue

**Comment by julianD77** [comment]
> https://rnfirebase.io/messaging/usage/ios-setup Seems like there are some additional configurations needed for iOS. Since I haven't enrolled for the developer program yet, I can not tell if this can fix the issue. Have anyone tried going through the process? If not, I'll be able to test in a few days.
> 
> Edit: I also found that some of the info is bit outdated, so instead of searching for "Push notifications" capability, you should select "Background Modes" and then check "Background fetch" and "Remote notifications" <img alt="image" width="461" src="https://user-images.githubusercontent.com/134609463/243170490-c8ec4943-63e9-4868-8cbf-019a5809b825.png">

In case useful, I can confirm that we have had Push Notifications working successfully on iOS with **only** the `Remote Notifications` Background Mode enabled in the App Capabilities section of XCode. So from our experience the `Background fetch` option does **not** need to be enabled in order to Push Notifications to be received by an App.

To the original error message of this ticket, we too have been seeing the _"You must be registered for remote messages before calling getToken..."_ error reported using v12.9.3 of the RN Firebase library (with RN 0.66.5) , despite our code path appearing to ensure that `getToken` is only ever called after `registerDeviceForRemoteMessages`.

We are due to release an update to v18.1.0 to see if this affects the frequency of this error and will report back here with the findings.

**Comment by sametcl2** [comment]
In my case, I had switched to a new branch and I got this error. I noticed that the push notification capability was gone in Xcode. My issue was resolved after adding this capability besides the Background fetch and Remote notifications mentioned above.

**Comment by julianD77** [comment]
That's interesting thanks @sametcl2 - I see now on reading all the above comments that both @feuermeister and @Yandamuri also found that ensuring both the 'Background fetch' and 'Remote notifications' are set apparently helped to remove the "You must be registered for remote messages before calling getToken" warning. 

After running into various build issues updating our `react-native-firebase` version above v15 due to the requirement to enable `use_frameworks` and the hermes issues detailed [here](https://rnfirebase.io/#altering-cocoapods-to-use-frameworks) (I think in part due to our now quite old RN version, 0.66.5) we will also try the simpler option of having both those values set in the App Capabilities as a stop gap, until we have updated our main `react-native` version and can then hopefully get back up to date with the latest RN firebase library

**Comment by arqummalik1** [comment]
> Same problem here, any solutions so far ? I'm using React Native CLI.
> 
> ` await messaging().registerDeviceForRemoteMessages();` i got this error:
> 
> > Usage of "messaging().registerDeviceForRemoteMessages()" is not required. You only need to register if auto-registration is disabled in your 'firebase.json' configuration file via the 'messaging_ios_auto_register_for_remote_messages' property.
> 
> if I remove registerDeviceForRemoteMessage
> 
> I got next error:
> 
> > [Error: [messaging/unregistered] You must be registered for remote messages before calling getToken, see messaging().registerDeviceForRemoteMessages().]

same here 
any solution ????

**Comment by michalpawlowski34** [comment]
> https://rnfirebase.io/messaging/usage/ios-setup Seems like there are some additional configurations needed for iOS. Since I haven't enrolled for the developer program yet, I can not tell if this can fix the issue. Have anyone tried going through the process? If not, I'll be able to test in a few days.
> 
> Edit: I also found that some of the info is bit outdated, so instead of searching for "Push notifications" capability, you should select "Background Modes" and then check "Background fetch" and "Remote notifications" <img alt="image" width="461" src="https://user-images.githubusercontent.com/134609463/243170490-c8ec4943-63e9-4868-8cbf-019a5809b825.png">

I have this configuration applied, the docs are updated tho - unfortunatelly I'm still getting the same error.

**Comment by arqummalik1** [comment]
> > https://rnfirebase.io/messaging/usage/ios-setup Seems like there are some additional configurations needed for iOS. Since I haven't enrolled for the developer program yet, I can not tell if this can fix the issue. Have anyone tried going through the process? If not, I'll be able to test in a few days.
> > Edit: I also found that some of the info is bit outdated, so instead of searching for "Push notifications" capability, you should select "Background Modes" and then check "Background fetch" and "Remote notifications" <img alt="image" width="461" src="https://user-images.githubusercontent.com/134609463/243170490-c8ec4943-63e9-4868-8cbf-019a5809b825.png">
> 
> I have this configuration applied, the docs are updated tho - unfortunatelly I'm still getting the same error.

i have resolved the issue just by going through docs , enabling Background Fetch. and Remote Notifications also Enabling Push Notifications in the Xcode-> Target-> Capabilities-> Push Notifications. Then Close the xcode and re-run the build .Hopefully it should resolve the issue. Thank you

**Comment by hamzakashifCL** [comment]
> https://rnfirebase.io/messaging/usage/ios-setup Seems like there are some additional configurations needed for iOS. Since I haven't enrolled for the developer program yet, I can not tell if this can fix the issue. Have anyone tried going through the process? If not, I'll be able to test in a few days.
> 
> Edit: I also found that some of the info is bit outdated, so instead of searching for "Push notifications" capability, you should select "Background Modes" and then check "Background fetch" and "Remote notifications" <img alt="image" width="461" src="https://user-images.githubusercontent.com/134609463/243170490-c8ec4943-63e9-4868-8cbf-019a5809b825.png">

Still getting the error even after applying this capability

**Comment by forbesgillikin** [comment]
I discovered some potentially useful information for this. Users who are experiencing this issue do not have the app in their notification settings _at all_. Meaning the app is missing entirely from Settings > Notifications.

Deleting and reinstalling the app does not help in any way. It appears this is an issue with the app registering for notifications with the device entirely, and not just related to the token.

**Comment by Biplovkumar** [comment]
```
    "@react-native-firebase/app": "^18.3.1",
    "@react-native-firebase/messaging": "^18.3.1",
    "react": "18.2.0",
    "react-native": "0.72.4",
```

Same error here! Please solve.

**Comment by Biplovkumar** [comment]
> I discovered some potentially useful information for this. Users who are experiencing this issue do not have the app in their notification settings _at all_. Meaning the app is missing entirely from Settings > Notifications.
> 
> Deleting and reinstalling the app does not help in any way. It appears this is an issue with the app registering for notifications with the device entirely, and not just related to the token.

It will give exact error. So that user can solve it.

**Comment by forbesgillikin** [comment]
> > I discovered some potentially useful information for this. Users who are experiencing this issue do not have the app in their notification settings _at all_. Meaning the app is missing entirely from Settings > Notifications.
> > Deleting and reinstalling the app does not help in any way. It appears this is an issue with the app registering for notifications with the device entirely, and not just related to the token.
> 
> It will give exact error. So that user can solve it.

I found that requesting permission for notifications can re-register a device and get them out of this state. Here is my work around

```js
try {
   await firebase.messaging().registerDeviceForRemoteMessages();
   const fcmToken = await messaging().getToken();
    // do something with the token
} catch () {
    await messaging().requestPermission();
}
```

**Comment by kakakalot** [comment]
> [Error: [messaging/unregistered] You must be registered for remote messages before calling getToken, see messaging().registerDeviceForRemoteMessages().]

I also facing the above issue after upgrading "@react-native-firebase/messaging" from `16.4.3` to `18.4.0`. Furthermore, I can provide more detail
Use cases:
1. App's fresh installation, open app, show notification permission alert, click allow. the `token` is available via `messaging().onTokenRefresh`. Then the app submits token to api and receive push notification successfully.
2. Force close or reinstall app, then open. The notification permission alert does not show and we got the above error message when calling `getToken`

**Comment by SirCameron** [comment]
@forbesgillikin permissions for notifications are allowed on my app and I still get this error.

**Comment by xerdnew** [comment]
I am also getting the same error. Any solution yet?
`    "@react-native-firebase/app": "^18.3.0",
    "@react-native-firebase/auth": "^18.3.0",
    "@react-native-firebase/messaging": "^18.3.0",
    "react": "18.2.0",
    "react-native": "0.72.5",
`

Running on iPhone 14 simulator with iOS 16.4

**Comment by nmluancs** [comment]
I think you forgot to enable push notification capability.

Click on .xcodeproj -> Capabilities -> Enable Push Notification

**Comment by SirCameron** [comment]
@nmluancs nope, added for debug and production...

**Comment by kakakalot** [comment]
Finally, after 1 month, I fixed this issus by using 
`[[UIApplication sharedApplication] registerForRemoteNotifications];`
instead of
`await messaging().registerDeviceForRemoteMessages()`

My AppDelegate.mm file
```obj-c
#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>

#import "RNFBMessagingModule.h"
#import <Firebase.h>
#import "RNSplashScreen.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }

  [FIRApp configureWithName:@"secondaryFromNative" options:[FIROptions defaultOptions]];
  // Add this line
  [[UIApplication sharedApplication] registerForRemoteNotifications];
  
  self.moduleName = @"SampleRN";
  self.initialProps = [RNFBMessagingModule addCustomPropsToUserProps:nil withLaunchOptions:@{}];

  [super application:application didFinishLaunchingWithOptions:launchOptions];

  [RNSplashScreen show];  // here
  return YES;
}

- (BOOL)application:(nonnull UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity restorationHandler:
#if defined(__IPHONE_OS_VERSION_MAX_ALLOWED) && (__IPHONE_OS_VERSION_MAX_ALLOWED >= 12000) /* __IPHONE_12_0 */
    (nonnull void (^)(NSArray<id <UIUserActivityRestoring>> *_Nullable))restorationHandler {
#else
  (nonnull void (^)(NSArray *_Nullable))restorationHandler {
#endif
  return NO;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

/// This method controls whether the `concurrentRoot`feature of React18 is turned on or off.
///
/// @see: https://reactjs.org/blog/2022/03/29/react-v18.html
/// @note: This requires to be rendering on Fabric (i.e. on the New Architecture).
/// @return: `true` if the `concurrentRoot` feature is enabled. Otherwise, it returns `false`.
- (BOOL)concurrentRootEnabled
{
  return true;
}

@end
```

**Comment by vauruk** [comment]
I followed all the tips but for me not worked until now. Someone other things to resolve the problem.

**Comment by nvdnvd00** [comment]
I've tried everything mentioned above, but nothing seems to work.
```
"react-native": "0.72.4",
"@react-native-firebase/app": "18.5.0",
"@react-native-firebase/auth": "18.5.0",
"@react-native-firebase/firestore": "18.5.0",
"@react-native-firebase/messaging": "^18.6.1",
```

**Comment by vauruk** [comment]
I used this way to pass off the problem of not registering etc, but I have another problem, I don't receive a message from firebase in iOS, in android it is ok!
this is my solution for now install this version: 

    "@react-native-firebase/analytics": "16.5.0",
    "@react-native-firebase/app": "16.5.0",
    "@react-native-firebase/messaging": "16.5.0",

I hope helped anyone.

**Comment by mikehardy** [comment]
I see people posting with version numbers that are not identical between all the react-native-firebase components: do not do that.

All versions should be the same --> https://invertase.io/blog/react-native-firebase-versioning

I see people posting that they have problems, but they are not using current versions of the software: do not do that

We issue new versions because they *solve problems*, and they could very well solve the problem you are experiencing. You would not want to spend a lot of time troubleshooting a problem with one of your users that you already fixed in your own software would you? You should not expect that here either.

**Comment by nvdnvd00** [comment]
> I see people posting with version numbers that are not identical between all the react-native-firebase components: do not do that.
> 
> All versions should be the same --> https://invertase.io/blog/react-native-firebase-versioning
> 
> I see people posting that they have problems, but they are not using current versions of the software: do not do that
> 
> We issue new versions because they _solve problems_, and they could very well solve the problem you are experiencing. You would not want to spend a lot of time troubleshooting a problem with one of your users that you already fixed in your own software would you? You should not expect that here either.

Even though I set all versions to be the same, the issue still persists (18.5.0/18.6.1)

**Comment by mikehardy** [comment]
Interesting, thank you for aligning versions and (hopefully...) using the current version (18.6.1) with the current version of firebase-ios-sdk (10.17.0 - you will get this automatically assuming you do not override the version)

There are a few reasons you might not *receive* messages:

- if it is a data only message, you must understand delivery is never guaranteed. If you watch Console.app on a plugged in physical device, you might see messages indicating the operating system received the message but just won't deliver it to the app. That happens all the time. They are unreliable by default. This is an Apple iOS decision. You cannot rely on data-only messages.
- If your app does not have notification permissions on iOS you won't see the message either
- If you were receiving messages sometimes on older versions (react-native-firebase v16 for instance) and now you are not on v18, perhaps you were not always correctly receiving an APNS token *and* firebase was using FCM directly while the app was foreground. Newer versions of firebase-ios-sdk never use FCM direct, they always use APNS *and* they will not let you register without a valid APNS token. There were many situations where the APNS token was invalid but previous firestore-ios-sdk versions would accept it anyway, leading to inconsistent behavior.
- there may be other reasons as well - perhaps there is a race condition in the AppDelegate swizzling that only shows up on some Apple hardware under certain conditions? Very difficult to say

Which of these is affecting you? Which is the problem? With an issue that has 70 comments, I bet every single one of these reasons is "the reason" for at least one person. Unfortunately that makes it impossible to ever close this issue (so many people! so many different issues!) and it makes it very difficult to handle each specific person (which reason is their reason?)

- call `firebase.messaging.getAPNSToken()` on current versions and see what you get. Hopefully it's a valid token
- plug a real device in to your development machine and watch the device logs (Xcode console output or Console.app with the device selected) and send an FCM to the device using it's specific token using a POST to the FCM REST API with a `notification` block in the FCM content, and watch what happens in the logs

That's the best advice I can give to start troubleshooting this stuff.

I am using a real device with a release build of the current firebase-ios-sdk and I am able to successfully receive FCM from it, so it is definitely possible for this to work. But it is difficult

**Comment by Akifcan** [comment]
in ios simulator  Authorization status: 1  but I can't get the device token(same error)

**Comment by Akifcan** [comment]
we tested on testlight now and notifications worked

**Comment by rmontana2023** [comment]
I'm still having this issue , when i released my app in test flight it cant generate token but in development mode it is working. any work around for this ?

**Comment by rmontana2023** [comment]
> we tested on testlight now and notifications worked

How did you fix it ?

**Comment by mikehardy** [comment]
@AlkanV you have mismatched firebase package versions, that is not supportable --> https://invertase.io/blog/react-native-firebase-versioning

You also have outdated package versions which is not something to approach support with as anyone involved (including yourself...) may waste precious time chasing an issue that is already fixed in current versions. Update to current, retest, re-post if still occurring please

**Comment by rmontana2023** [comment]
Hi @mikehardy i already update my firebase package version 

` "@react-native-firebase/app": "^18.6.1",
 "@react-native-firebase/messaging": "^18.6.1",`

But i still encounter inconsistency in generating the apns token when the app is released/testflight 
I try it on multiple devices some device that is not connected to wifi only cellular data the APNS token is working. Any help on this ?

**Comment by mikehardy** [comment]
I'm sorry, I'm not sure why it is inconsistent. I have not experienced this that I'm aware of.
This would be a workaround, but perhaps if you retried a few times it might come through? It is a network-dependent process so maybe there is something to do with network access / network blocking on the wifi network or maybe there is latency or something and a retry would work.

**Comment by rmontana2023** [comment]
Thank you, and also in my local environment apns token is working but when i upload my app to testflight fcm token is null.

**Comment by redwolf-rohit** [comment]
try using messaging().requestPermission():

`async function requestUserPermission() {
    const authStatus = await messaging().requestPermission();
    console.log(authStatus);
    const enabled =
      authStatus === messaging.AuthorizationStatus.AUTHORIZED ||
      authStatus === messaging.AuthorizationStatus.PROVISIONAL;

    if (enabled) {
      console.log('Authorization status:', authStatus);
    }

    return enabled;
}
  

try{
 const permissionStatus = await requestUserPermission();

  if (permissionStatus && !messaging().isDeviceRegisteredForRemoteMessages) {
    await messaging().registerDeviceForRemoteMessages();
  }
}catch(error){
   console.log(error)
}`

**Comment by redwolf-rohit** [comment]
`try using messaging().requestPermission():

`async function requestUserPermission() {
    const authStatus = await messaging().requestPermission();
    console.log(authStatus);
    const enabled =
      authStatus === messaging.AuthorizationStatus.AUTHORIZED ||
      authStatus === messaging.AuthorizationStatus.PROVISIONAL;

    if (enabled) {
      console.log('Authorization status:', authStatus);
    }

    return enabled;
}
  

try{
 const permissionStatus = await requestUserPermission();

  if (permissionStatus && !messaging().isDeviceRegisteredForRemoteMessages) {
    await messaging().registerDeviceForRemoteMessages();
  }
}catch(error){
   console.log(error)
}``

**Comment by ateeq4112** [comment]
Add push notification capability  on tab singing & Capabilities in xcode and then rebuild project.

**Comment by incom-app-ru** [comment]
I had this problem. I was able to solve it.

In XCode - Signing & Capabilities.
add Background fetch & add Remote notification (Background Modes)
add Push Notifications

for **Debug** and  for **Release** separately!

**Comment by timorss** [comment]
still happens

**Comment by kakakalot** [comment]
> still happens

@timorss , Did you try my solution? It is [here](https://github.com/invertase/react-native-firebase/issues/6829#issuecomment-1759437762)

**Comment by timorss** [comment]
> > still happens
> 
> @timorss , Did you try my solution? It is [here](https://github.com/invertase/react-native-firebase/issues/6829#issuecomment-1759437762)

yes 

![image](https://github.com/invertase/react-native-firebase/assets/13855015/ebceed92-a88e-4f28-b3a4-62dbbc9fd9b6)

**Comment by mkhitarbdoyan** [comment]
useEffect(() => {

    const initializeNotifications = async () => {
      try {
        if (Platform.OS === 'android') {
          await checkAndRequestPermission();
        }
        await messaging().registerDeviceForRemoteMessages();
        await messaging().requestPermission();
        const initialToken = await messaging().getToken();
        if (initialToken) {
          handleTokenRefresh(initialToken);
        }

        notifee.onBackgroundEvent(handleBackgroundEvent);
        unmountHandlers.push( notifee.onForegroundEvent(handleForegroundEvent));
        unmountHandlers.push(messaging().onTokenRefresh(handleTokenRefresh));
        unmountHandlers.push(messaging().onMessage(handleMessage));
        unmountHandlers.push(messaging().onNotificationOpenedApp(handleNotificationOpenedApp));
      } catch (error) {
        console.error('Error initializing notifications:', error);
      }
    };

    initializeNotifications();

    return () => {
      unmountHandlers.forEach((handler) => handler());
    };

  }, []);

  return null;
};
Could you say what’s rong whit this anp whay I I’m getting this error . Thanks :)
 ERROR  Error initializing notifications: [Error: [messaging/unregistered] You must be registered for remote messages before calling getToken, see messaging().registerDeviceForRemoteMessages().]

**Comment by tungne** [comment]
> I didnt add push notifications, I Solved it by adding it ![image](https://private-user-images.githubusercontent.com/13855015/303995551-2fdf61a0-bdf4-4f13-80e2-34bd67210a44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2Mzk1ODYsIm5iZiI6MTcxODYzOTI4NiwicGF0aCI6Ii8xMzg1NTAxNS8zMDM5OTU1NTEtMmZkZjYxYTAtYmRmNC00ZjEzLTgwZTItMzRiZDY3MjEwYTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDE1NDgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwNzA0OTBjMDFiNGJmYjk5N2QzNDkwNzNmNDY1OWZhZDU0ODIxM2Q5NDI4ZTIyNzI3ZmJjYmIyMGM2ZDgxNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y8wh8ezHcdxcif6LZMY-LSQjtectECqLjB7Ew8eJd9g)
> 
> https://rnfirebase.io/messaging/usage/ios-setup

thank bro

**Comment by tungne** [comment]
> I didnt add push notifications, I Solved it by adding it ![image](https://private-user-images.githubusercontent.com/13855015/303995551-2fdf61a0-bdf4-4f13-80e2-34bd67210a44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2Mzk1ODYsIm5iZiI6MTcxODYzOTI4NiwicGF0aCI6Ii8xMzg1NTAxNS8zMDM5OTU1NTEtMmZkZjYxYTAtYmRmNC00ZjEzLTgwZTItMzRiZDY3MjEwYTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDE1NDgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwNzA0OTBjMDFiNGJmYjk5N2QzNDkwNzNmNDY1OWZhZDU0ODIxM2Q5NDI4ZTIyNzI3ZmJjYmIyMGM2ZDgxNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y8wh8ezHcdxcif6LZMY-LSQjtectECqLjB7Ew8eJd9g)
> 
> https://rnfirebase.io/messaging/usage/ios-setup

This is the solution that helped me solve the problem. Thanks, bro.

**Comment by Kaijonsson** [comment]
I found a pretty ugly workaround, but it works for me as for now.

[ await registerForRemoteMessages()
      //delay the fcm token fetch with 500 milliseconds
      //this seems to prevent the function from throwing error that the fcm token is not available
      //TODO: investigate why this is needed and if there is a better way to handle this
      await new Promise((resolve) => setTimeout(resolve, 500))
      const FCMToken = await getFCMToken()](url)
      
      
      Hope it can get people forward while waiting for a proper solution.

**Comment by jaaywags** [comment]
I get this error on a fresh expo project running on iOS Simulator on my M3 Mac

> You must be registered for remote messages before calling getToken, see messaging().registerDeviceForRemoteMessages().

I tried both with and without `await messaging().registerDeviceForRemoteMessages();`.

I have the aps-environment entitlement in my app.json

```json
{
  "expo": {
    ...
    "ios": {
      ...
      "entitlements": {
        "aps-environment": "production"
      }
    },
...
}
```

I also added the p8 file to firebase and made sure all my certificates and keys are setup correctly in the apple developer console.
