### ISSUE TITLE
Getting two notifications in foreground only.

### ISSUE THREAD

**Issue by mksmanishp** [invertase/react-native-firebase#8214]
I am using Firebase Cloud Messaging (FCM) to send data-only messages in my React Native app. However, when a notification is received in the foreground, I am getting two notifications in the handler.

` 
  const getFCMToken = async () => {
    try {
      let fcmToken = await AsyncStorage.getItem('fcmToken');
      console.log('******** fcmToken 1', fcmToken);

      if (!fcmToken) {
        // Get the FCM token
        fcmToken = await messaging().getToken();
        await AsyncStorage.setItem('fcmToken', fcmToken);
      }
      let data = {fcm_token: fcmToken};
      console.log('yvguhbijn', data);
      let response = await HomeService.postFCMToken(data);
      if (response?.data?.success) {
        Toast.show('FCM set successfully');
      }
    } catch (error) {
      console.error('Error getting FCM token:', error);
    }
  };

  const displayBgContent = async remoteMessage => {
    const {data} = remoteMessage;

    // Generate a default title and body if not provided
    const title = data?.title;
    const body = data?.body;

    // Safely parse the actions field
    let actions = [];
    try {
      const parsedActions = JSON.parse(data?.actions || '[]'); // Parse or default to an empty array
      actions = parsedActions.map(action => ({
        title: action.name.toUpperCase(), // Example: "BUY"
        pressAction: {
          id: action.name, // Example: "buy"
          launchActivity: 'default',
        },
      }));
    } catch (error) {
      console.error('Failed to parse actions:', error);
    }
    // Check if the image URL exists and is valid
    const image = data?.image && data.image.trim() !== '' ? data.image : null;

    // Display notification using notifee
    if (actions.length == 0) {
      await notifee.displayNotification({
        title,
        body,
        android: {
          channelId: 'default',
          smallIcon: 'notification_icon', // Ensure you have this icon in your project
          largeIcon: image || 'default_icon', // Fallback to a local image if no valid URL
          importance: AndroidImportance.HIGH,
          pressAction: {
            id: 'default',
          },
          badge: true,
          color: '#FF7900',
          onlyAlertOnce: true,
          style: image
            ? {
                type: AndroidStyle.BIGPICTURE, // Show a big picture style notification
                picture: image,
              }
            : undefined, // Skip style if no image
        },
        ios: {
          foregroundPresentationOptions: {
            badge: true,
            sound: true,
            banner: true,
            list: true,
          },
          categoryId: 'customCategory', // Match the category ID registered earlier
          sound: 'default', // Notification sound
          attachments: image
            ? [
                {
                  url: image, // Attach image only if it exists
                },
              ]
            : [], // Empty array if no image
        },
        data, // Include the original payload for further handling
      });
    } else {
      await notifee.displayNotification({
        title,
        body,
        android: {
          channelId: 'default',
          smallIcon: 'notification_icon', // Ensure you have this icon in your project
          largeIcon: image || 'default_icon', // Fallback to a local image if no valid URL
          importance: AndroidImportance.HIGH,
          actions: actions, // Attach dynamic actions
          badge: true,
          color: '#FF7900',
          onlyAlertOnce: true,
          style: image
            ? {
                type: AndroidStyle.BIGPICTURE, // Show a big picture style notification
                picture: image,
              }
            : undefined, // Skip style if no image
        },
        ios: {
          foregroundPresentationOptions: {
            badge: true,
            sound: true,
            banner: true,
            list: true,
          },
          categoryId: 'customCategory', // Match the category ID registered earlier
          sound: 'default', // Notification sound
          attachments: image
            ? [
                {
                  url: image, // Attach image only if it exists
                },
              ]
            : [], // Empty array if no image
        },
        data, // Include the original payload for further handling
      });
    }
  };

  const listenToInAppNotifications = async () => {
    const unsubscribe = messaging().onMessage(async remoteMessage => {
      await displayBgContent(remoteMessage);
      const {messageId} = remoteMessage;

      if (!messageId) {
        return;
      }

      // Cancel the notification after displaying it
      try {
        await notifee.cancelNotification(messageId);
        console.log(`Notification with ID ${messageId} canceled successfully`);
      } catch (error) {
        console.error(`Failed to cancel notification with ID ${messageId}:`, error);
      }
    });

    return unsubscribe;
  };

` 
Getting two notifications in both android and ios.I am using firebase messaging and notifee for displaying the notifications.

**Comment by mikehardy** [comment]
If you are using data-only, then the only notifications posted will be from your own code
If you are seeing two notifications, then your own code is posting them twice - *somehow*. It's Occam's razor - this is the most likely explanation. Look very very very carefully for listeners registered twice or code paths that might post two.

There is no one else experiencing this problem on both platforms - the only known way this ever happened where it was not project-specific code was in (now-obsolete) iOS 18.0 where the notification center would erroneously double-post the same GCM message-id notification. That is now fixed. There are no other reports.

**Comment by ukcasso** [comment]
@mikehardy 
hello.
Is it right for users to handle it regardless? I'm still having this problem.

https://github.com/invertase/react-native-firebase/issues/7836
This problem seems similar.

**Comment by farazahmed12** [comment]
same here

**Comment by rkchoudhury** [comment]
Hi [mikehardy](https://github.com/mikehardy) - I am getting double notifications in foreground mode for the iOS 18.0.1 device only.

I have used following notifee & fcm version. Could you please help me which version has the fixes? Or do I need to change any code from the implementation point of view.

```js
"@notifee/react-native": "9.1.8",
"@react-native-firebase/messaging": "20.0.0",
```
