### ISSUE TITLE
[🐛] FirebaseAuth/FirebaseAuth-Swift.h file not found in React Native iOS project

### ISSUE THREAD

**Issue by patras1** [invertase/react-native-firebase#8271]
**Description:**
I am encountering an issue while integrating Firebase Authentication into my React Native iOS project. The build fails with the following error:

```
'FirebaseAuth/FirebaseAuth-Swift.h' file not found
```

I have already tried the recommended solutions, including adding `use_frameworks! :linkage => :static` to my `Podfile`, but the issue persists.

### **Podfile:**
```ruby
def node_require(script)
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

setup_permissions([
  'Microphone',
  'SpeechRecognition',
])

use_frameworks! :linkage => :static  # Fix for FirebaseAuth issue

target 'cookie_app' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'cookie_appTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
```

### **Environment:**

- **React Native Version:** [e.g., 0.73.0]
- **Xcode Version:** [e.g., 15.0]
- **CocoaPods Version:** [e.g., 1.12.0]
- **Platform:** iOS
- **Firebase Packages Used:**
  - `Firebase/Auth`
  - `Firebase/Core`
- **Development Machine:** [e.g., MacBook M1, Intel-based Mac]

### **Steps to Reproduce:**

1. Install Firebase dependencies:
   ```sh
   cd ios
   pod install --repo-update
   ```
2. Run the project:
   ```sh
   npx react-native run-ios
   ```
3. Build fails with the error `'FirebaseAuth/FirebaseAuth-Swift.h' file not found`

### **What I Have Tried:**

✅ Added `use_frameworks! :linkage => :static` in `Podfile`
✅ Ensured `GoogleService-Info.plist` is correctly added to the Xcode project
✅ Ran `pod install --repo-update`
✅ Cleaned the build folder (`cmd + shift + K` in Xcode) and recompiled
✅ Deleted `node_modules`, `Pods`, and `Podfile.lock`, then reinstalled dependencies:

```sh
rm -rf node_modules ios/Pods ios/Podfile.lock
yarn install
cd ios && pod install
```

✅ Checked that `ENABLE_BITCODE` is set to `NO` in Xcode settings

### **Expected Behavior:**

The project should build successfully without the `FirebaseAuth/FirebaseAuth-Swift.h` error.

### **Actual Behavior:**

The build fails with the `'FirebaseAuth/FirebaseAuth-Swift.h' file not found` error.

### **Additional Context:**

I am aware that a similar issue has already been reported and closed on GitHub, but the proposed solutions have not worked for me. If there are any additional workarounds or fixes, please let me know. Any help would be appreciated!

**Thank you!** 🙏

**Comment by mikehardy** [comment]
> I have already tried the recommended solutions, including adding use_frameworks! :linkage => :static to my Podfile, but the issue persists.

The only thing I can think of is that you did not do this in such a way that the Podfile actually had this in there, or you did not then `pod install` and build correctly.

It is literally the only reason this would happen - that use_frameworks wasn't applied correctly.

**Comment by patras1** [comment]
I did add it to the pod file (you can see the pod file) and run "pod install", still the some error.

**Comment by mikehardy** [comment]
I see what you're saying. But my script runs successfully. I'm using it right now even. So I've got evidence right in front of my eyes of it working. Hard to ignore that.

**Comment by sagar-khichi27** [comment]
getting the same issue too

**Comment by sagar-khichi27** [comment]
"@react-native-firebase/auth": "^21.7.2",
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Fritou' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'FritouTests' do
    inherit! :complete
    # Pods for testing
  end

  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseAuth', :modular_headers => true
  pod 'FirebaseAuthInterop', :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'RecaptchaInterop', :modular_headers => true

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
  thats my pod file i am getting the same error try everything put  :app_path static tooo but still getting same issue

**Comment by mikehardy** [comment]
@sagar-khichi27 this is basically illegal for react-native-firebase, you'll get no support here, you must remove this:

```

pod 'Firebase', :modular_headers => true
pod 'FirebaseCoreInternal', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true
pod 'FirebaseAuth', :modular_headers => true
pod 'FirebaseAuthInterop', :modular_headers => true
pod 'FirebaseAppCheckInterop', :modular_headers => true
pod 'FirebaseCoreExtension', :modular_headers => true
pod 'RecaptchaInterop', :modular_headers => true


```

You must use `use_frameworks! :linkage => :static`. it will fix your problem.

**Comment by patras1** [comment]
It seems there might be another issue causing this problem. After running the installation, I don’t see the FirebaseAuth/FirebaseAuth-Swift.h file in its expected location.

Is there any additional information I can provide to help investigate the cause?

Thanks!

**Comment by quvonchbekyunusov** [comment]
> [@sagar-khichi27](https://github.com/sagar-khichi27) this is basically illegal for react-native-firebase, you'll get no support here, you must remove this:
> 
> ```
> 
> pod 'Firebase', :modular_headers => true
> pod 'FirebaseCoreInternal', :modular_headers => true
> pod 'GoogleUtilities', :modular_headers => true
> pod 'FirebaseCore', :modular_headers => true
> pod 'FirebaseAuth', :modular_headers => true
> pod 'FirebaseAuthInterop', :modular_headers => true
> pod 'FirebaseAppCheckInterop', :modular_headers => true
> pod 'FirebaseCoreExtension', :modular_headers => true
> pod 'RecaptchaInterop', :modular_headers => true
> ```
> 
> You must use `use_frameworks! :linkage => :static`. it will fix your problem.

If I delete these, I get the following problem:

[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `FirebaseAuth` depends upon `FirebaseAuthInterop`, `FirebaseAppCheckInterop`, `FirebaseCore`, `FirebaseCoreExtension`, `GoogleUtilities`, and `RecaptchaInterop`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

The Swift pod `FirebaseCoreInternal` depends upon `GoogleUtilities`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

**Comment by quvonchbekyunusov** [comment]
it is my pod file

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
end

target 'tezparcel' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end

pod install or pod install --repo-update=> i get this error: 
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `FirebaseAuth` depends upon `FirebaseAuthInterop`, `FirebaseAppCheckInterop`, `FirebaseCore`, `FirebaseCoreExtension`, `GoogleUtilities`, and `RecaptchaInterop`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

The Swift pod `FirebaseCoreInternal` depends upon `GoogleUtilities`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

When I add this lines in pod file 

pod 'FirebaseAuthInterop', :modular_headers => true
pod 'FirebaseAppCheckInterop', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true
pod 'FirebaseCoreExtension', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true
pod 'RecaptchaInterop', :modular_headers => true
pod 'Firebase' 
pod 'FirebaseAuth'

I get this error => 'FirebaseAuth/FirebaseAuth-Swift.h' file not found

It is my package.json =>
{
  "name": "tezparcel",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@adrianso/react-native-barcode-builder": "^1.0.13",
    "@cherry-soft/react-native-basic-pagination": "^1.0.6",
    "@gluestack-style/react": "latest",
    "@gluestack-ui/config": "latest",
    "@gluestack-ui/themed": "latest",
    "@hookform/resolvers": "^3.10.0",
    "@invertase/react-native-apple-authentication": "^2.4.0",
    "@react-native-async-storage/async-storage": "^2.1.1",
    "@react-native-community/datetimepicker": "^8.3.0",
    "@react-native-community/netinfo": "^11.4.1",
    "@react-native-documents/picker": "^10.1.0",
    "@react-native-firebase/app": "^21.7.1",
    "@react-native-firebase/auth": "^21.7.1",
    "@react-native-firebase/messaging": "^21.7.1",
    "@react-native-google-signin/google-signin": "^13.1.0",
    "@react-native-masked-view/masked-view": "^0.3.2",
    "@react-navigation/elements": "^2.2.5",
    "@react-navigation/native": "^7.0.14",
    "@react-navigation/native-stack": "^7.2.0",
    "@reduxjs/toolkit": "^2.5.1",
    "axios": "^1.7.9",
    "i18next": "^24.2.2",
    "i18next-http-backend": "^3.0.2",
    "lottie-react-native": "5.1.6",
    "moment": "^2.30.1",
    "react": "18.3.1",
    "react-i18next": "^15.4.0",
    "react-native": "0.77.0",
    "react-native-base64": "^0.2.1",
    "react-native-bootsplash": "^6.3.3",
    "react-native-countdown-circle-timer": "^3.2.1",
    "react-native-fast-image": "^8.6.3",
    "react-native-file-viewer": "^2.1.5",
    "react-native-fs": "^2.20.0",
    "react-native-gifted-chat": "^2.6.5",
    "react-native-iconify": "^2.0.3",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-modal": "^13.0.1",
    "react-native-modal-datetime-picker": "^18.0.0",
    "react-native-pager-view": "^6.7.0",
    "react-native-reanimated": "^3.16.7",
    "react-native-responsive-sizes": "^2.0.4",
    "react-native-safe-area-context": "^5.2.0",
    "react-native-screens": "^4.6.0",
    "react-native-svg": "^15.11.1",
    "react-native-swiper": "^1.6.0",
    "react-native-tab-view": "^4.0.5",
    "react-native-timeline-flatlist": "^0.8.0",
    "react-native-toast-message": "^2.2.1",
    "react-native-webview": "^13.13.2",
    "react-query": "^3.39.3",
    "react-redux": "^9.2.0",
    "react-timer-hook": "^3.0.8",
    "redux-persist": "^6.0.0",
    "rn-fetch-blob": "^0.12.0",
    "yup": "^1.6.1"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@babel/preset-env": "^7.25.3",
    "@babel/runtime": "^7.25.0",
    "@react-native-community/cli": "15.0.1",
    "@react-native-community/cli-platform-android": "15.0.1",
    "@react-native-community/cli-platform-ios": "15.0.1",
    "@react-native/babel-preset": "0.77.0",
    "@react-native/eslint-config": "0.77.0",
    "@react-native/metro-config": "0.77.0",
    "@react-native/typescript-config": "0.77.0",
    "@types/jest": "^29.5.13",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.3.1",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
}


Does anyone have a solution for this?

**Comment by mikehardy** [comment]
@quvonchbekyunusov I will repeat - you must use `use_frameworks! :linkage => :static`. It appears you removed the workarounds that are all that `modular_headers` junk but did not correctly get your Podfile set up to use_frameworks.

No additional information will help troubleshoot this

I encourage every single person that has this issue to make a minimal reproduction to prove to yourself it works.

Create a fresh new example app with no modules.
Add only `@react-native-firebase/app` and follow it's installation instructions.

Do the pod install and ios build. It should work.

In fact, that's exactly what https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh does (it just does all the firebase modules, but same idea: create empty test app, do basic integration, prove it works)

**Comment by patras1** [comment]
Found the solution I think:

# right after `use_frameworks! :linkage => :static`
$RNFirebaseAsStaticFramework = true

**Comment by mikehardy** [comment]
Indeed, this is documented - 
https://rnfirebase.io/#altering-cocoapods-to-use-frameworks

<img width="658" alt="Image" src="https://github.com/user-attachments/assets/eeb7d316-0fbd-41a5-85ca-8efd9493a844" />

If you were not doing that and you are now, then that was indeed the integration error in your project and you should be all set now, fantastic

**Comment by debacodes10** [comment]
I am having the same issue with a react native app. my file configurations are as follows
Podfile:
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_modular_headers!
  #use_frameworks! :linkage => static
  $RNFirebaseAsStaticFramework = true
end

target 'routinelyApp' do
  config = use_native_modules!
  # pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  # pod 'FirebaseAuth', :modular_headers => true
  # pod 'FirebaseCoreInternal', :modular_headers => true  
  # # pod 'FirebaseStorageInternal', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'FirebaseAuthInterop', :modular_headers => true
  # # pod 'FirebaseMessagingInterop', :modular_headers => true
  # pod 'GTMSessionFetcher', :modular_headers => true
  # pod 'FirebaseAppCheckInterop', :modular_headers => true
  # pod 'FirebaseAuthInterop', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'RecaptchaInterop', :modular_headers => true

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end

AppDelegate.mm
import UIKit
import React
import React_RCTAppDelegate
import ReactAppDependencyProvider
#import <Firebase.h>

@main
class AppDelegate: RCTAppDelegate {
  override func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
    [FIRApp configure];
    self.moduleName = "routinelyApp"
    self.dependencyProvider = RCTAppDependencyProvider()

    // You can add your custom initial props in the dictionary below.
    // They will be passed down to the ViewController used by React Native.
    self.initialProps = [:]

    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  override func sourceURL(for bridge: RCTBridge) -> URL? {
    self.bundleURL()
  }

  override func bundleURL() -> URL? {
#if DEBUG
    RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index")
#else
    Bundle.main.url(forResource: "main", withExtension: "jsbundle")
#endif
  }
}

**Comment by debacodes10** [comment]
### Issue: Firebase Auth Integration with React Native

I am facing the same issue trying to implement Firebase Auth with React Native.

#### **Podfile**
```ruby
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => static
  $RNFirebaseAsStaticFramework = true
end

target 'routinelyApp' do
  config = use_native_modules!
  # pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  # pod 'FirebaseAuth', :modular_headers => true
  # pod 'FirebaseCoreInternal', :modular_headers => true  
  # # pod 'FirebaseStorageInternal', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'FirebaseAuthInterop', :modular_headers => true
  # # pod 'FirebaseMessagingInterop', :modular_headers => true
  # pod 'GTMSessionFetcher', :modular_headers => true
  # pod 'FirebaseAppCheckInterop', :modular_headers => true
  # pod 'FirebaseAuthInterop', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'RecaptchaInterop', :modular_headers => true

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
```

#### **AppDelegate.mm**
``` ruby
import UIKit
import React
import React_RCTAppDelegate
import ReactAppDependencyProvider
#import <Firebase.h>

@main
class AppDelegate: RCTAppDelegate {
  override func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
    [FIRApp configure];
    self.moduleName = "routinelyApp"
    self.dependencyProvider = RCTAppDependencyProvider()

    // You can add your custom initial props in the dictionary below.
    // They will be passed down to the ViewController used by React Native.
    self.initialProps = [:]

    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  override func sourceURL(for bridge: RCTBridge) -> URL? {
    self.bundleURL()
  }

  override func bundleURL() -> URL? {
#if DEBUG
    RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index")
#else
    Bundle.main.url(forResource: "main", withExtension: "jsbundle")
#endif
  }
}
```

**Comment by mikehardy** [comment]
> I am facing the same issue trying to implement Firebase Auth with React Native.

Because you are using the same invalid-for-support-you-have-to-remove-it `modular_headers` stuff.

Don't do that. I've written about it multiple times, in this very issue.

Anyone that uses modular_headers stuff in their Podfile is going to have compilation problems and waste everyone's time - especially their own! - trying to get it to work. Stop

**Comment by debacodes10** [comment]
> > I am facing the same issue trying to implement Firebase Auth with React Native.
> 
> Because you are using the same invalid-for-support-you-have-to-remove-it `modular_headers` stuff.
> 
> Don't do that. I've written about it multiple times, in this very issue.
> 
> Anyone that uses modular_headers stuff in their Podfile is going to have compilation problems and waste everyone's time - especially their own! - trying to get it to work. Stop

Okay tried doing that and now I have the following error
### Error: Couldn't install Pods. Updating the Pods project and trying again...

#### Command `pod install` failed.
**Cause:**  
The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `FirebaseAuth` depends upon:  
- `FirebaseAuthInterop`  
- `FirebaseAppCheckInterop`  
- `FirebaseCore`  
- `FirebaseCoreExtension`  
- `GoogleUtilities`  
- `RecaptchaInterop`  

These dependencies do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may:  
- Set `use_modular_headers!` globally in your Podfile, **or**  
- Specify `:modular_headers => true` for particular dependencies.

The Swift pod `FirebaseCoreInternal` depends upon:  
- `GoogleUtilities`  

This dependency does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may:  
- Set `use_modular_headers!` globally in your Podfile, **or**  
- Specify `:modular_headers => true` for particular dependencies.

#### Terminal Output:
```sh
pod install --repo-update --ansi exited with non-zero code: 1
```
could you give me a workaround for modular headers that won't break the pods installation? I've been stuck on this for a few days and I have no other resources to work this out

**Comment by erkutr-prog** [comment]
> linkage = ENV['USE_FRAMEWORKS']
> if linkage != nil
>   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
>   use_frameworks! :linkage => static
>   $RNFirebaseAsStaticFramework = true
> end

In this part your linkage may be nil and if statement may not be working. That was my issue.

**Comment by mikehardy** [comment]
Look - if you are using react-native-firebase there is no question that you simply must have `use_frameworks! :linkage => :static`

Why leave it to chance with conditionals based on environment etc? Remove all that stuff. Just make it a plan statement:

```ruby
use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true
```

done. no conditionals that might go wrong, no guessing, just set it right in there.

**Comment by jpunlay** [comment]
To resolve this error `Pods/RNFBAuth: 'FirebaseAuth/FirebaseAuth-Swift.h' file not found`. These are the steps I followed:
```sh
cd ios
npx expo prebuild --clean
pod install --repo-update --ansi # optional if running into issues during the previous step
```

As stated in other comments, **add** these lines to your ios/Podfile
```ruby
use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true
```

And **remove** this line
```ruby
use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
```
Then, I was able to run the project without issues

```sh
cd .. # to root
npx expo run:ios --device   
```

**Comment by timotismjntk** [comment]
> > > > linkage = ENV['USE_FRAMEWORKS']
> > > > if linkage != nil
> > > > Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
> > > > use_frameworks! :linkage => static
> > > > $RNFirebaseAsStaticFramework = true
> > > > end
> > > 
> > > 
> > > If you're using react-native 0.77, In this part your linkage may be nil and if statement may not be working. That was my issue.
> > 
> > 
> > Can you share your podfile or maybe just this specific section of it? Since I'm still getting a file not found error for Firebase auth/FirebaseAuth-Swift.h even when I tried setting it up as a clean project with nothing but firebase and firebaseauth.
> 
> I made a workaround like this:
> 
> ```
> linkage = ENV['USE_FRAMEWORKS'] || 'static'
> if linkage != nil
>   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
>   use_frameworks! :linkage => :static
>   $RNFirebaseAsStaticFramework = true
> end
> ```
> 
> But again i'm not sure if it's the best practice and if you actually have an ENV variable named 'USE_FRAMEWORK' you should set it to some value.
> 
> Edit: You should not use modular_headers btw.

thanks bro, this solution is worked fine

**Comment by debacodes10** [comment]
> To resolve this error `Pods/RNFBAuth: 'FirebaseAuth/FirebaseAuth-Swift.h' file not found`. These are the steps I followed:
> ```sh
> cd ios
> npx expo prebuild --clean
> pod install --repo-update --ansi # optional if running into issues during the previous step
> ```
> 
> As stated in other comments, **add** these lines to your ios/Podfile
> ```ruby
> use_frameworks! :linkage => :static
> $RNFirebaseAsStaticFramework = true
> ```
> 
> And **remove** this line
> ```ruby
> use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
> ```
> Then, I was able to run the project without issues
> 
> ```sh
> cd .. # to root
> npx expo run:ios --device   
> ```
> 
> 

Well since then I've moved to supabase for my firebase requirements, but I'll definitely try this fix in the future on a minimalistic project just to test out the firebase integration. However, you mentioned using expo commands here, but my requirements are for a bare react native project without expo. In that case, do you have any solutions?

**Comment by manualexSP** [comment]
Hello everyone, so this is such an old issue, and somehow I'm still facing it every time I work with Firebase on a new project.
So yes, `use_frameworks! :linkage => :static` or `use_modular_headers!` might solve the problem. But my issue with those 2 is that the impact will be over ALL packages that I used. And in my case, some of them didn't work with this change.

And the solution is:
```
static_frameworks = [
  'FirebaseAuthInterop',
  'FirebaseAppCheckInterop',
  'FirebaseCore',
  'FirebaseCoreExtension',
  'GoogleUtilities',
  'RecaptchaInterop',
  'FirebaseCore',
  'FirebaseInstallations',
  'GoogleDataTransport',
  'nanopb',
  'FirebaseABTesting',
  'FirebaseAuth',
]

pre_install do |installer|
  installer.pod_targets.each do |pod|
    if static_frameworks.include?(pod.name)
      puts "Configuring #{pod.name} as static framework"
      def pod.build_type
        Pod::BuildType.new(:linkage => :static, :packaging => :framework)
      end
    end
  end
end
```

Just set the pods that you need to be static...
No more need to add the pods like this   `pod 'FirebaseCore', :modular_headers => true`
And no need of `use_frameworks! :linkage => :static` or `use_modular_headers!`

Be sure you clean the project properly after you add this change.

With the mention that this fix depends on what react native and Firebase you have. But this should fix all your problems.
Hope it helps.

**Comment by Etaliya** [comment]
```
    "@react-native-firebase/app": "^22.2.1",
    "@react-native-firebase/auth": "^22.2.1",
    "@react-native-firebase/firestore": "^22.2.1",
    "@react-native/new-app-screen": "0.80.0",
    "react": "19.1.0",
    "react-native": "0.80.0"
```

I'm still having this issue, with this version

**Comment by jsnavarroc** [comment]
# 👇 Thanks to @manualexSP for this solution shared in:
# https://github.com/invertase/react-native-firebase/issues/8271
#
# This setup fixes the error:
# `'FirebaseAuth/FirebaseAuth-Swift.h' file not found`
# without requiring `use_frameworks!` or `use_modular_headers!` globally,
# which can potentially break compatibility with other React Native dependencies.
#
# Be sure to clean your project properly after applying this change:
# - rm -rf ios/Pods
# - rm -rf ios/Podfile.lock
# - cd ios && pod install --repo-update
# - Clean Build Folder in Xcode

static_frameworks = [
  'FirebaseAuthInterop',
  'FirebaseAppCheckInterop',
  'FirebaseCore',
  'FirebaseCoreExtension',
  'GoogleUtilities',
  'RecaptchaInterop',
  'FirebaseCore',
  'FirebaseInstallations',
  'GoogleDataTransport',
  'nanopb',
  'FirebaseABTesting',
  'FirebaseAuth',
]

pre_install do |installer|
  installer.pod_targets.each do |pod|
    if static_frameworks.include?(pod.name)
      puts "Configuring #{pod.name} as static framework"
      def pod.build_type
        Pod::BuildType.new(:linkage => :static, :packaging => :framework)
      end
    end
  end
end

**Comment by jsnavarroc** [comment]
Huge thanks to **@manualexSP** for this brilliant solution:
[https://github.com/invertase/react-native-firebase/issues/8271](https://github.com/invertase/react-native-firebase/issues/8271)

This resolves the `'FirebaseAuth/FirebaseAuth-Swift.h' file not found` error without needing to use `use_frameworks!` or `use_modular_headers!` globally, which could break compatibility with other React Native libraries.

If you're using FirebaseAuth and run into Swift header import issues, just configure the following pods as static frameworks. This solved everything for me.

🔧 Be sure to clean your project before rebuilding:

* `rm -rf ios/Pods ios/Podfile.lock`
* `cd ios && pod install --repo-update`
* Clean build folder in Xcode

Here’s the working `Podfile` snippet:

```ruby
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

static_frameworks = [
  'FirebaseAuthInterop',
  'FirebaseAppCheckInterop',
  'FirebaseCore',
  'FirebaseCoreExtension',
  'GoogleUtilities',
  'RecaptchaInterop',
  'FirebaseCoreInternal',
  'FirebaseInstallations',
  'GoogleDataTransport',
  'nanopb',
  'FirebaseABTesting',
  'FirebaseAuth'
]

pre_install do |installer|
  installer.pod_targets.each do |pod|
    if static_frameworks.include?(pod.name)
      puts "Configuring #{pod.name} as static framework"
      def pod.build_type
        Pod::BuildType.new(:linkage => :static, :packaging => :framework)
      end
    end
  end
end

target 'YourTargetNameHere' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'FirebaseAuth'
  pod 'FirebaseAuthInterop'
  pod 'FirebaseAppCheckInterop'
  pod 'FirebaseCore'
  pod 'FirebaseCoreExtension'
  pod 'FirebaseCoreInternal'
  pod 'GoogleUtilities'
  pod 'RecaptchaInterop'
  pod 'nanopb'
  pod 'FirebaseABTesting'
  pod 'FirebaseInstallations'
  pod 'GoogleDataTransport'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
        config.build_settings['DEFINES_MODULE'] = 'YES'
      end
    end
  end
end
```

Again, thank you @manualexSP — this workaround saved me hours! Would be amazing if this could be integrated upstream so we don't have to patch Podfiles manually in the future.

**Comment by Etaliya** [comment]
> Huge thanks to **[@manualexSP](https://github.com/manualexSP)** for this brilliant solution: [#8271](https://github.com/invertase/react-native-firebase/issues/8271)
> 
> This resolves the `'FirebaseAuth/FirebaseAuth-Swift.h' file not found` error without needing to use `use_frameworks!` or `use_modular_headers!` globally, which could break compatibility with other React Native libraries.
> 
> If you're using FirebaseAuth and run into Swift header import issues, just configure the following pods as static frameworks. This solved everything for me.
> 
> 🔧 Be sure to clean your project before rebuilding:
> 
> * `rm -rf ios/Pods ios/Podfile.lock`
> * `cd ios && pod install --repo-update`
> * Clean build folder in Xcode
> 
> Here’s the working `Podfile` snippet:
> 
> require Pod::Executable.execute_command('node', ['-p',
>   'require.resolve(
>     "react-native/scripts/react_native_pods.rb",
>     {paths: [process.argv[1]]},
>   )', __dir__]).strip
> 
> platform :ios, min_ios_version_supported
> prepare_react_native_project!
> 
> static_frameworks = [
>   'FirebaseAuthInterop',
>   'FirebaseAppCheckInterop',
>   'FirebaseCore',
>   'FirebaseCoreExtension',
>   'GoogleUtilities',
>   'RecaptchaInterop',
>   'FirebaseCoreInternal',
>   'FirebaseInstallations',
>   'GoogleDataTransport',
>   'nanopb',
>   'FirebaseABTesting',
>   'FirebaseAuth'
> ]
> 
> pre_install do |installer|
>   installer.pod_targets.each do |pod|
>     if static_frameworks.include?(pod.name)
>       puts "Configuring #{pod.name} as static framework"
>       def pod.build_type
>         Pod::BuildType.new(:linkage => :static, :packaging => :framework)
>       end
>     end
>   end
> end
> 
> target 'YourTargetNameHere' do
>   config = use_native_modules!
> 
>   use_react_native!(
>     :path => config[:reactNativePath],
>     :app_path => "#{Pod::Config.instance.installation_root}/.."
>   )
> 
>   pod 'FirebaseAuth'
>   pod 'FirebaseAuthInterop'
>   pod 'FirebaseAppCheckInterop'
>   pod 'FirebaseCore'
>   pod 'FirebaseCoreExtension'
>   pod 'FirebaseCoreInternal'
>   pod 'GoogleUtilities'
>   pod 'RecaptchaInterop'
>   pod 'nanopb'
>   pod 'FirebaseABTesting'
>   pod 'FirebaseInstallations'
>   pod 'GoogleDataTransport'
> 
>   post_install do |installer|
>     react_native_post_install(
>       installer,
>       config[:reactNativePath],
>       :mac_catalyst_enabled => false
>     )
> 
>     installer.pods_project.targets.each do |target|
>       target.build_configurations.each do |config|
>         config.build_settings['SWIFT_VERSION'] = '5.0'
>         config.build_settings['DEFINES_MODULE'] = 'YES'
>       end
>     end
>   end
> end
> Again, thank you [@manualexSP](https://github.com/manualexSP) — this workaround saved me hours! Would be amazing if this could be integrated upstream so we don't have to patch Podfiles manually in the future.

It's work for me.

**Comment by meTech1021** [comment]
Thank you! @mikehardy 
Your solution helped me alot!

**Comment by muhammadqazi** [comment]
> Huge

This worked finally !!!

`pod install --repo-update`

```
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

static_frameworks = [
  'FirebaseAuthInterop',
  'FirebaseAppCheckInterop',
  'FirebaseCore',
  'FirebaseCoreExtension',
  'GoogleUtilities',
  'RecaptchaInterop',
  'FirebaseCoreInternal',
  'FirebaseInstallations',
  'GoogleDataTransport',
  'nanopb',
  'FirebaseABTesting',
  'FirebaseAuth'
]

pre_install do |installer|
  installer.pod_targets.each do |pod|
    if static_frameworks.include?(pod.name)
      puts "Configuring #{pod.name} as static framework"
      def pod.build_type
        Pod::BuildType.new(:linkage => :static, :packaging => :framework)
      end
    end
  end
end

target 'YourTargetNameHere' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'FirebaseAuth'
  pod 'FirebaseAuthInterop'
  pod 'FirebaseAppCheckInterop'
  pod 'FirebaseCore'
  pod 'FirebaseCoreExtension'
  pod 'FirebaseCoreInternal'
  pod 'GoogleUtilities'
  pod 'RecaptchaInterop'
  pod 'nanopb'
  pod 'FirebaseABTesting'
  pod 'FirebaseInstallations'
  pod 'GoogleDataTransport'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
        config.build_settings['DEFINES_MODULE'] = 'YES'
      end
    end
  end
end
```

**Comment by mikehardy** [comment]
> without needing to use use_frameworks!

use_frameworks is a requirement of our upstream native SDK, people can do whatever workarounds they like trying to avoid that but none of it will be integrated here nor will it be officially supported. It is simply not supportable to go against a stated requirement of a native SDK when you are entirely based on that native SDK...

**Comment by PSSubramanya** [comment]
> Look - if you are using react-native-firebase there is no question that you simply must have `use_frameworks! :linkage => :static`
> 
> Why leave it to chance with conditionals based on environment etc? Remove all that stuff. Just make it a plain statement:
> 
> use_frameworks! :linkage => :static
> $RNFirebaseAsStaticFramework = true
> done. no conditionals that might go wrong, no guessing, just set it right in there.

This is perfect. Remove the conditionality and add these lines and it should work perfectly. Thankyou.

**Comment by BhattJayD** [comment]
> Hello everyone, so this is such an old issue, and somehow I'm still facing it every time I work with Firebase on a new project. So yes, `use_frameworks! :linkage => :static` or `use_modular_headers!` might solve the problem. But my issue with those 2 is that the impact will be over ALL packages that I used. And in my case, some of them didn't work with this change.
> 
> And the solution is:
> 
> ```
> static_frameworks = [
>   'FirebaseAuthInterop',
>   'FirebaseAppCheckInterop',
>   'FirebaseCore',
>   'FirebaseCoreExtension',
>   'GoogleUtilities',
>   'RecaptchaInterop',
>   'FirebaseCore',
>   'FirebaseInstallations',
>   'GoogleDataTransport',
>   'nanopb',
>   'FirebaseABTesting',
>   'FirebaseAuth',
> ]
> 
> pre_install do |installer|
>   installer.pod_targets.each do |pod|
>     if static_frameworks.include?(pod.name)
>       puts "Configuring #{pod.name} as static framework"
>       def pod.build_type
>         Pod::BuildType.new(:linkage => :static, :packaging => :framework)
>       end
>     end
>   end
> end
> ```
> 
> Just set the pods that you need to be static... No more need to add the pods like this `pod 'FirebaseCore', :modular_headers => true` And no need of `use_frameworks! :linkage => :static` or `use_modular_headers!`
> 
> Be sure you clean the project properly after you add this change.
> 
> With the mention that this fix depends on what react native and Firebase you have. But this should fix all your problems. Hope it helps.


Thanks for this!

**Comment by Meenu1796** [comment]
Thank you!!!!! it totally worked for me...
