### ISSUE TITLE
[🐛] Android build failing v21.7.2

### ISSUE THREAD

**Issue by bhandanyan-nomad** [invertase/react-native-firebase#8281]
## Issue

When upgrading from v21.7.1 to v21.7.2, I am getting an Android build failure. I am  attempting to upgrade both `"@react-native-firebase/analytics"` and `"@react-native-firebase/app"`, which are the only two packages my app uses.

The relevant error output is:
```
> Task :app:compileProductionReleaseKotlin FAILED
e: file:///root/.gradle/caches/8.10.2/transforms/a1268c39ffb7db38a824ecc3933bd041/transformed/play-services-measurement-impl-22.2.0-api.jar!/META-INF/java.com.google.android.gms.libs.filecompliance.proto_file_access_api_type_kt_proto_lite.kotlin_moduleModule was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.1.0, expected version is 1.9.0.
e: file:///root/.gradle/caches/8.10.2/transforms/a1268c39ffb7db38a824ecc3933bd041/transformed/play-services-measurement-impl-22.2.0-api.jar!/META-INF/third_party.kotlin.protobuf.src.commonMain.kotlin.com.google.protobuf.kotlin_only_for_use_in_proto_generated_code_its_generator_and_tests.kotlin_moduleModule was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.1.0, expected version is 1.9.0.
e: file:///root/.gradle/caches/8.10.2/transforms/a1268c39ffb7db38a824ecc3933bd041/transformed/play-services-measurement-impl-22.2.0-api.jar!/META-INF/third_party.kotlin.protobuf.src.commonMain.kotlin.com.google.protobuf.kotlin_shared_runtime.kotlin_moduleModule was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.1.0, expected version is 1.9.0.
e: file:///root/.gradle/caches/8.10.2/transforms/b67e2c6721a0a91c5190ddd0ff47a80a/transformed/play-services-measurement-api-22.2.0-api.jar!/META-INF/java.com.google.android.gmscore.integ.client.measurement_api_measurement_api.kotlin_moduleModule was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.1.0, expected version is 1.9.0.

> Task :app:mergeProductionReleaseAssets

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileProductionReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
info Fetching system and libraries information...
System:
  OS: macOS 15.2
  CPU: (12) arm64 Apple M2 Pro
  Memory: 759.05 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: ~/.nvm/versions/node/v20.10.0/bin/node
  Yarn:
    version: 1.22.22
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v20.10.0/bin/npm
  Watchman:
    version: 2024.09.30.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /Users/benjamin/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.9971841
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.13
    path: /usr/bin/javac
  Ruby:
    version: 3.3.5
    path: /Users/benjamin/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.1.3
    wanted: 15.1.3
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.6
    wanted: 0.76.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `21.7.2`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ajmal0197** [comment]
This issue just wasted my day. For now switching to 
    `"@react-native-firebase/analytics": "^21.6.1",`

**Comment by mikehardy** [comment]
Android build error reported by two people, zero android build files included, no way to reproduce, so closing as no template.

There cannot be an expectation of reproduction and help with no relevant details.

I'll note that we *did* update some android dependencies between 21.7.1 and 21.7.2 but they are non-breaking:

https://github.com/invertase/react-native-firebase/blob/main/CHANGELOG.md#bug-fixes

If there is a build failure after them, I wonder what would happen if you cleaned the android gradle build cache. In a non-expo context that would be `cd android && ./gradlew clean`, then try rebuilding. With no relevant details can't really tailor the advice though.

We do not reproduce locally on dev machines nor in CI though - it's building android cleanly (or we wouldn't have released...)

**Comment by bhandanyan-nomad** [comment]
What information can I provide that would be most helpful for investigating the issue?

**Comment by mikehardy** [comment]
The standard answer is "all relevant details". We do our best to keep that list correct in the issue template which was ignored as this bug was opened.

In general, you want to pre-answer all the questions you would ask someone else if someone else posed this problem to you

https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

I provide an MCVE to everyone that is ready to run and works for me, and results in successful builds at all times (or I don't release react-native-firebase...)

https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

So the bar to keeping a build issue open without it being closed as "project-specific" / "no repository change required" is pretty high. But I'm open to their being an issue *if it can be demonstrated*

**Comment by mikehardy** [comment]
(note that in rnfbdemo I updated successfully to the versions mentioned here two days ago, and it's already pre-qualifying the release of firebase-ios-sdk 11.8.1 - no problems...)

**Comment by bhandanyan-nomad** [comment]
I added some redacted versions of my android files. Private project so i can't share everything as a full reproduction. I can try to make a reproduction, but it may take several days for me to find the time and successfully recreate the conditions.

Thought I'd quickly open the issue anyway to flag a potential issue, and have it be there for others to contribute to.

**Comment by mikehardy** [comment]
```groovy
    // Iterable
    // https://mvnrepository.com/artifact/com.google.firebase/firebase-messaging
    implementation("com.google.firebase:firebase-messaging:23.0.2")
```

really bad idea to specify this version - react-native-firebase expects to be in control of all firebase versions via use of the firebase bill of materials. Strongly suggest removing the version specifier

>     wanted: 0.76.6

It's possible react-native 0.77.0 will work better? Our e2e app is working with 0.76 so doubtful, but rnfbdemo tests 0.77

I haven't heard report on suggested test:

> If there is a build failure after them, I wonder what would happen if you cleaned the android gradle build cache. In a non-expo context that would be cd android && ./gradlew clean, then try rebuilding. With no relevant details can't really tailor the advice though.

Clean builds should be working, my working hypothesis is you have some local build cache pollution.

**Comment by bhandanyan-nomad** [comment]
I tried:
* removing pinned firebase messaging version and the error persists
* Upgrading `com.google.gms:google-services` from 4.3.15 to 4.4.2 and the error persists


My test builds use these fastlane steps, so I always have a clean before a build
```ruby
  desc "Clean android build artifacts"
  lane :clean do
    gradle(task: "clean")
  end

  private_lane :clean_and_build do |options|
    clean()
    gradle(
      task: 'bundle',
      flavor: options[:app_flavor],
      build_type: 'Release',
      properties: $gradle_properties
    )
  end

  desc "Use this to test building the app locally. Especially useful when upgrading dependency versions"
  lane :test_build do
    clean_and_build(app_flavor: "Production")
  end
```

I hope to get to upgrading react-native to v0.77 in the next couple weeks, so I will probably come back to this again after.

I really appreciate your suggestions to try to resolve this issue Mike, thank you for taking the time. If I'm able to create a proper reproduction I will open a new issue.
