### ISSUE TITLE
Failed to find byte code for com/google/firebase [any unused module]

### ISSUE THREAD

**Issue by IljaDaderko** [invertase/react-native-firebase#915]
### Issue

I upgraded to android studio 3.1 today and gradle 3.1 that came out and started getting these errors

> Failed to find byte code for com/google/android/gms/ads/VideoController$VideoLifecycleCallbacks

> Failed to find byte code for com/google/firebase/storage/StreamDownloadTask$StreamProcessor

> Failed to find byte code for com/google/firebase/database/ChildEventListener

etc... all of these are firebase modules I currently don't use in my project i.e I don't have anything like 

```gradle
compile 'com.google.firebase:firebase-database:11.8.0'
```
in my `app/build.gradle` as I don't use it. I also submitted a question at stack overflow regarding this: https://stackoverflow.com/questions/49518556/failed-to-find-byte-code-for-com-google-firebase

Where they suggested to actually include any erorring modules and this does indeed fix the issue, but I had to add a ton of them, which I don't think is necessary?

Fact that this happens to almost all firebase dependencies that I don't use and can only assume are used in RNFirebase I think this is an issue?

### Environment

1. Application Target Platform: Android

2. Development Operating System: macOS High Siera

3. Build Tools: Android Studio 3.1, Android SDK 26, com.android.tools.build:gradle:3.1.0

4. React Native version: 0.54.3

5. RNFirebase Version: 3.3.1

6. Firebase Module: Any unused module

**Comment by chrisbianca** [comment]
@IljaDaderko any chance you could try the latest code from master and see whether its fixed?  Just did some changes to migrate to the new Gradle dependency configurations: https://github.com/invertase/react-native-firebase/commit/7f7169bd0884ba53962ed24815298a28a2682acf

Alternatively, try making the equivalent changes locally to see if it fixes the issue...

**Comment by IljaDaderko** [comment]
@chrisbianca will give it a shot as soon as I am done with my main work. Could be related to compile being deprecated.

When we include firebase modules in our own projects, I assume we should use `implementation` instead of compile?

**Comment by chrisbianca** [comment]
Great, thanks.  Yeah, I've switched our tests app over to using `implementation` and this seems to work.  Although I couldn't actually reproduce the errors you were seeing to be able to confirm it's fixed your problem.

**Comment by IljaDaderko** [comment]
There was one other guy in Stack Overflow question I mentioned having same issues with 3.3 after upgrading to latest gradle by the way.

**Comment by IljaDaderko** [comment]
@chrisbianca ok, so I basically swapped `android/build.gradle` in my node_modules with your change and it got past that error 👍 

I'm not sure if this is already fixed in v4 but now this is popping up

```
error: RNFirebaseAdMobRewardedVideo is not abstract and does not override abstract method onRewardedVideoCompleted() in RewardedVideoAdListener
```

I'm not using adMob module in project, so not sure if its still related to this issue. Let me know if I should close and open another one.

I will run v4 this weekend to see if it fixes these issues, as there are few things I need to change according to the docs to make it work.

**Comment by chrisbianca** [comment]
Awesome, thanks for the confirmation!

Yes, that is fixed in v4 - it's a result of some API changes in v12 of the Firebase Android libs

**Comment by IljaDaderko** [comment]
As a side note, my project has all changes you made to test app as well, so if yours is working on v4, I think mine will as well 👍

**Comment by chrisbianca** [comment]
We're going to get another RC of v4 out shortly - once we have, we'll close this issue off.

We're unlikely to backport this to v3 due to the complications with getting it working across multiple gradle versions.

**Comment by chrisbianca** [comment]
v4.0.0-rc.3 is out now.

Check out the release notes for instructions on how to upgrade gradle: https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0-rc.3

**Comment by IljaDaderko** [comment]
@chrisbianca I updated my project to v4.0.0-rc.3 just now, started getting these errors again.
As this didn't make much sense to me I tired to reset all caches I can think of

1) Deleted my projects `/build`, `.iml` files
2) Deleted `/.gradle` folder from my macs home dir
3) Reinstalled my node modules (deleted them, deleted package-lock, ran `npm cache verify`)

And am still getting the error

I went and compared build.gradle from rc3 that I have in android studio with changes you referenced https://github.com/invertase/react-native-firebase/commit/7f7169bd0884ba53962ed24815298a28a2682acf, everything is identical.

My nest step was to compare my android setup with your test app setup and there is one differences, but nothing I can see that would cause this, I have `com.google.gms:google-services:3.2.0`

My dependencies are
```
dependencies {
    implementation fileTree(include: ["*.jar"], dir: "libs")
    implementation "com.android.support:appcompat-v7:27.1.0"
    implementation "com.google.android.gms:play-services-base:12.0.0"
    implementation "com.google.android.gms:play-services-auth:12.0.0"
    implementation "com.google.firebase:firebase-core:12.0.0"
    implementation "com.google.firebase:firebase-auth:12.0.0"
    implementation "com.google.firebase:firebase-firestore:12.0.0"
    implementation "com.google.firebase:firebase-invites:12.0.0"
    implementation "com.google.firebase:firebase-messaging:12.0.0"
    implementation "com.facebook.react:react-native:+"
    implementation project(":react-native-device-info")
    implementation project(":react-native-fbsdk")
    implementation(project(":rn-google-sign-in")){
        exclude group: "com.google.android.gms"
    }
    implementation(project(":react-native-firebase")) {
        transitive = false
    }
}
```

I am currently getting errors related to database / adMob etc.. all modules I don't use
> Failed to find byte code for com/google/firebase/storage/OnPausedListener

**Comment by IljaDaderko** [comment]
And as expected it all worked once I added (not propper solution however, correct?)

```
    // Don't need these
    implementation "com.google.firebase:firebase-ads:12.0.1"
    implementation "com.google.firebase:firebase-config:12.0.1"
    implementation "com.google.firebase:firebase-crash:12.0.1"
    implementation "com.google.firebase:firebase-database:12.0.1"
    implementation "com.google.firebase:firebase-perf:12.0.1"
    implementation "com.google.firebase:firebase-storage:12.0.1"
    // END Don't need these
```

**Comment by chrisbianca** [comment]
@IljaDaderko It looks like this is a known issue in 3.1 :( https://issuetracker.google.com/issues/72811718

If you disable instant run this should start working for you again.

**Comment by IljaDaderko** [comment]
Gotcha, thank you for bug reference, shame they released with this :/

**Comment by sequencer08** [comment]
Same issue here. Any fixes for this?

**Comment by IljaDaderko** [comment]
@sequencer08 3 options

1) Disable instant run in android studio
2) Add all firebase modules
3) Upgrade to gradle 3.1.1

**Comment by sequencer08** [comment]
Hi @IljaDaderko, Thanks for the suggestion. I able to fixed the issue by including all the firebase modules since I already upgraded the gradle to 3.1.1. But is there any option except including all firebase modules? For me, I think It's not necessary to include what I'm not using. Big thanks 😄

**Comment by IljaDaderko** [comment]
@sequencer08 honestly I'd just disable instant run in android studio, its not needed for react native projects imho. Googling how to do so should solve your issue 👍 Its android studio specific, when you build with cli you won't see the issue.

**Comment by zkrige** [comment]
Disabling instant run fixed this

**Comment by EKoetsjarjan** [comment]
Failed to find byte code for com/google/firebase/database/DatabaseReference$CompletionListener

disabling instant run fixed it for for me too (android studio 3.2.1)

**Comment by artyom-developer** [comment]
same bugs :( help
